// ═══════════════════════════════════════════════════════════════════════════════
// CharacterCreationState.cs
// Entity maintaining all player selections throughout the character creation
// process. Supports forward/backward navigation while preserving choices until
// final confirmation. Transient entity — not persisted to the database; only
// the final character is saved.
// Version: 0.17.5a
// ═══════════════════════════════════════════════════════════════════════════════

namespace RuneAndRust.Domain.Entities;

using Microsoft.Extensions.Logging;
using RuneAndRust.Domain.Enums;
using RuneAndRust.Domain.Extensions;
using RuneAndRust.Domain.Interfaces;
using RuneAndRust.Domain.ValueObjects;

/// <summary>
/// Maintains all player selections throughout the character creation process.
/// Supports forward/backward navigation while preserving choices until final confirmation.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="CharacterCreationState"/> is a transient entity that exists only during
/// the character creation session. It tracks the player's current step, all selections
/// made across the six creation steps, and metadata about the session itself. The state
/// is not persisted to the database — only the final <c>PlayerCharacter</c> entity is
/// saved upon confirmation.
/// </para>
/// <para>
/// The state supports the following operations:
/// </para>
/// <list type="bullet">
///   <item>
///     <description>
///       <see cref="TryAdvance"/>: Validates the current step's requirements and
///       advances to the next step if met.
///     </description>
///   </item>
///   <item>
///     <description>
///       <see cref="TryGoBack"/>: Navigates to the previous step while preserving
///       all existing selections.
///     </description>
///   </item>
///   <item>
///     <description>
///       <see cref="IsStepComplete"/>: Checks whether a specific step has all required
///       selections in place.
///     </description>
///   </item>
///   <item>
///     <description>
///       <see cref="Reset"/>: Clears all selections and returns to Step 1 (Lineage).
///     </description>
///   </item>
/// </list>
/// <para>
/// The <see cref="IsComplete"/> computed property returns <c>true</c> only when all
/// required selections are present and there are no validation errors. This is the
/// precondition for character creation confirmation.
/// </para>
/// <para>
/// Each step stores its selection in a nullable property. Properties are <c>null</c>
/// until the player makes a selection for that step. The Clan-Born lineage additionally
/// requires a <see cref="FlexibleAttributeBonus"/> selection before advancing.
/// </para>
/// </remarks>
/// <seealso cref="CharacterCreationStep"/>
/// <seealso cref="CharacterCreationStepExtensions"/>
public class CharacterCreationState : IEntity
{
    // ═══════════════════════════════════════════════════════════════════════════
    // PRIVATE FIELDS
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Logger for detailed diagnostic output during state creation and navigation.
    /// </summary>
    private static ILogger<CharacterCreationState>? _logger;

    // ═══════════════════════════════════════════════════════════════════════════
    // PROPERTIES — Identity
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Gets the unique identifier for this creation state.
    /// </summary>
    /// <value>
    /// A <see cref="Guid"/> that uniquely identifies this creation state instance.
    /// Generated by the <see cref="Create"/> factory method.
    /// </value>
    public Guid Id { get; private set; }

    /// <summary>
    /// Gets the session identifier for this creation workflow.
    /// Used to track creation sessions across potential interruptions.
    /// </summary>
    /// <value>
    /// A 32-character hexadecimal string (GUID with no hyphens) that uniquely
    /// identifies this creation session. Generated by the <see cref="Create"/>
    /// factory method.
    /// </value>
    public string SessionId { get; private set; }

    /// <summary>
    /// Gets or sets the current step in the creation workflow.
    /// </summary>
    /// <value>
    /// The <see cref="CharacterCreationStep"/> representing where the player
    /// currently is in the six-step creation wizard. Defaults to
    /// <see cref="CharacterCreationStep.Lineage"/> on creation.
    /// </value>
    public CharacterCreationStep CurrentStep { get; set; }

    // ═══════════════════════════════════════════════════════════════════════════
    // PROPERTIES — Step 1: Lineage
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Gets or sets the selected lineage (blood heritage).
    /// Null until Step 1 is completed.
    /// </summary>
    /// <value>
    /// The selected <see cref="Lineage"/> value, or <c>null</c> if Step 1 has
    /// not yet been completed. Determines attribute modifiers, passive bonuses,
    /// and Trauma Economy baseline.
    /// </value>
    public Lineage? SelectedLineage { get; set; }

    /// <summary>
    /// Gets or sets the flexible attribute bonus selection for Clan-Born lineage.
    /// Required when <see cref="SelectedLineage"/> is <see cref="Lineage.ClanBorn"/>;
    /// null otherwise.
    /// </summary>
    /// <value>
    /// The <see cref="CoreAttribute"/> chosen for the Clan-Born +1 flexible bonus,
    /// or <c>null</c> if the lineage is not Clan-Born or not yet selected.
    /// </value>
    /// <remarks>
    /// <para>
    /// Clan-Born lineage grants a +1 bonus to any single core attribute of the
    /// player's choice. This sub-selection must be completed before the player
    /// can advance from Step 1. Non-Clan-Born lineages ignore this property.
    /// </para>
    /// </remarks>
    public CoreAttribute? FlexibleAttributeBonus { get; set; }

    // ═══════════════════════════════════════════════════════════════════════════
    // PROPERTIES — Step 2: Background
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Gets or sets the selected background (pre-Silence profession).
    /// Null until Step 2 is completed.
    /// </summary>
    /// <value>
    /// The selected <see cref="Background"/> value, or <c>null</c> if Step 2
    /// has not yet been completed. Determines starting skills and equipment.
    /// </value>
    public Background? SelectedBackground { get; set; }

    // ═══════════════════════════════════════════════════════════════════════════
    // PROPERTIES — Step 3: Attributes
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Gets or sets the attribute allocation mode (Simple or Advanced).
    /// Defaults to <see cref="AttributeAllocationMode.Simple"/> for new players.
    /// </summary>
    /// <value>
    /// The <see cref="AttributeAllocationMode"/> determining whether attributes
    /// are auto-set from a recommended build (Simple) or manually allocated
    /// via point-buy (Advanced).
    /// </value>
    public AttributeAllocationMode AttributeAllocationMode { get; set; }

    /// <summary>
    /// Gets or sets the attribute allocation state.
    /// Contains point allocation for all five core attributes.
    /// </summary>
    /// <value>
    /// The <see cref="AttributeAllocationState"/> tracking current attribute values,
    /// points spent, and points remaining, or <c>null</c> if Step 3 has not yet
    /// been started.
    /// </value>
    public AttributeAllocationState? Attributes { get; set; }

    // ═══════════════════════════════════════════════════════════════════════════
    // PROPERTIES — Step 4: Archetype (PERMANENT)
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Gets or sets the selected archetype (combat role).
    /// PERMANENT CHOICE — Cannot be changed after character creation.
    /// Null until Step 4 is completed.
    /// </summary>
    /// <value>
    /// The selected <see cref="Archetype"/> value, or <c>null</c> if Step 4
    /// has not yet been completed. Determines starting abilities, resource pools,
    /// and available specializations.
    /// </value>
    /// <remarks>
    /// <para>
    /// This is the only permanent choice in the character creation workflow.
    /// Once the character is confirmed, the archetype cannot be changed.
    /// The UI displays a prominent warning before the player confirms this selection.
    /// </para>
    /// </remarks>
    public Archetype? SelectedArchetype { get; set; }

    // ═══════════════════════════════════════════════════════════════════════════
    // PROPERTIES — Step 5: Specialization
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Gets or sets the selected specialization (tactical identity).
    /// Must be valid for the selected archetype.
    /// Null until Step 5 is completed.
    /// </summary>
    /// <value>
    /// The selected <see cref="SpecializationId"/> value, or <c>null</c> if Step 5
    /// has not yet been completed. Must belong to the selected archetype's available
    /// specializations.
    /// </value>
    public SpecializationId? SelectedSpecialization { get; set; }

    // ═══════════════════════════════════════════════════════════════════════════
    // PROPERTIES — Step 6: Summary
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Gets or sets the character name entered during the summary step.
    /// Subject to validation rules (2-20 characters, letters/spaces/hyphens only).
    /// Null until name is entered.
    /// </summary>
    /// <value>
    /// The character name string, or <c>null</c> if no name has been entered.
    /// Must pass validation rules defined in <c>creation-workflow.json</c>.
    /// </value>
    public string? CharacterName { get; set; }

    // ═══════════════════════════════════════════════════════════════════════════
    // PROPERTIES — Metadata
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Gets the timestamp when this creation session was started.
    /// </summary>
    /// <value>
    /// A UTC <see cref="DateTime"/> recording when <see cref="Create"/> was called.
    /// </value>
    public DateTime CreatedAt { get; private set; }

    /// <summary>
    /// Gets or sets the timestamp when this state was last modified.
    /// Updated on every selection change and navigation action.
    /// </summary>
    /// <value>
    /// A UTC <see cref="DateTime"/> recording the most recent state modification.
    /// </value>
    public DateTime LastModifiedAt { get; set; }

    /// <summary>
    /// Gets a value indicating whether all required selections are complete.
    /// True when all steps have valid selections and name is validated.
    /// </summary>
    /// <value>
    /// <c>true</c> if all six steps have selections and there are no validation
    /// errors; <c>false</c> otherwise. This is the precondition for character
    /// creation confirmation.
    /// </value>
    /// <remarks>
    /// <para>
    /// Checks that every step has a non-null selection:
    /// </para>
    /// <list type="bullet">
    ///   <item><description>Step 1: Lineage selected</description></item>
    ///   <item><description>Step 2: Background selected</description></item>
    ///   <item><description>Step 3: Attributes allocated</description></item>
    ///   <item><description>Step 4: Archetype selected</description></item>
    ///   <item><description>Step 5: Specialization selected</description></item>
    ///   <item><description>Step 6: Character name entered</description></item>
    ///   <item><description>No validation errors present</description></item>
    /// </list>
    /// <para>
    /// Note: This property checks for the presence of selections, not their
    /// detailed validity. Use <see cref="IsStepComplete"/> for per-step
    /// validation that includes business rules (e.g., Clan-Born flexible bonus).
    /// </para>
    /// </remarks>
    public bool IsComplete =>
        SelectedLineage.HasValue &&
        SelectedBackground.HasValue &&
        Attributes.HasValue &&
        SelectedArchetype.HasValue &&
        SelectedSpecialization.HasValue &&
        !string.IsNullOrWhiteSpace(CharacterName) &&
        ValidationErrors.Count == 0;

    /// <summary>
    /// Gets or sets the list of validation errors for the current state.
    /// Empty list indicates valid state.
    /// </summary>
    /// <value>
    /// A <see cref="List{T}"/> of validation error messages. Empty when the state
    /// has no errors.
    /// </value>
    public List<string> ValidationErrors { get; set; } = new();

    // ═══════════════════════════════════════════════════════════════════════════
    // CONSTRUCTORS
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Private constructor for EF Core materialization.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Required by Entity Framework Core for entity materialization from database
    /// queries. Not intended for direct use — use <see cref="Create"/> instead.
    /// </para>
    /// </remarks>
    private CharacterCreationState()
    {
        SessionId = null!;
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // FACTORY METHODS
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Creates a new character creation state with a unique session ID.
    /// </summary>
    /// <param name="logger">
    /// Optional logger for diagnostic output during state creation and navigation.
    /// If provided, enables detailed logging of state transitions.
    /// </param>
    /// <returns>
    /// An initialized <see cref="CharacterCreationState"/> at Step 1 (Lineage)
    /// with all selections set to <c>null</c>, attribute mode set to Simple,
    /// and empty validation errors.
    /// </returns>
    /// <remarks>
    /// <para>
    /// Initializes a fresh creation session with:
    /// </para>
    /// <list type="bullet">
    ///   <item><description>Unique <see cref="Id"/> (new GUID)</description></item>
    ///   <item><description>Unique <see cref="SessionId"/> (32-char hex string)</description></item>
    ///   <item><description><see cref="CurrentStep"/> set to <see cref="CharacterCreationStep.Lineage"/></description></item>
    ///   <item><description><see cref="AttributeAllocationMode"/> set to <see cref="Enums.AttributeAllocationMode.Simple"/></description></item>
    ///   <item><description>All step selections set to <c>null</c></description></item>
    ///   <item><description>Timestamps set to current UTC time</description></item>
    /// </list>
    /// </remarks>
    /// <example>
    /// <code>
    /// var state = CharacterCreationState.Create();
    /// // state.CurrentStep == CharacterCreationStep.Lineage
    /// // state.IsComplete == false
    /// </code>
    /// </example>
    /// <seealso cref="Reset"/>
    public static CharacterCreationState Create(ILogger<CharacterCreationState>? logger = null)
    {
        _logger = logger;

        _logger?.LogDebug(
            "Creating new character creation state. Generating session ID and initializing defaults.");

        var now = DateTime.UtcNow;
        var sessionId = Guid.NewGuid().ToString("N");

        var state = new CharacterCreationState
        {
            Id = Guid.NewGuid(),
            SessionId = sessionId,
            CurrentStep = CharacterCreationStep.Lineage,
            AttributeAllocationMode = AttributeAllocationMode.Simple,
            CreatedAt = now,
            LastModifiedAt = now,
            ValidationErrors = new List<string>()
        };

        _logger?.LogInformation(
            "Character creation session started. SessionId: {SessionId}, CurrentStep: {CurrentStep}, " +
            "AttributeAllocationMode: {AttributeAllocationMode}, CreatedAt: {CreatedAt}",
            state.SessionId, state.CurrentStep, state.AttributeAllocationMode, state.CreatedAt);

        return state;
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // NAVIGATION METHODS
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Advances to the next step if current step requirements are met.
    /// </summary>
    /// <returns>
    /// <c>true</c> if the state advanced to the next step; <c>false</c> if
    /// the current step is incomplete or the current step is the final step.
    /// </returns>
    /// <remarks>
    /// <para>
    /// Validates that the current step has all required selections via
    /// <see cref="IsStepComplete"/> before advancing. If validation fails
    /// or the current step is Summary (no next step), returns <c>false</c>
    /// without modifying the state.
    /// </para>
    /// <para>
    /// On successful advance, updates <see cref="CurrentStep"/> to the next
    /// step and refreshes <see cref="LastModifiedAt"/>.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// var state = CharacterCreationState.Create();
    /// state.SelectedLineage = Lineage.IronBlooded;
    /// bool advanced = state.TryAdvance(); // true — advances to Background
    /// </code>
    /// </example>
    /// <seealso cref="TryGoBack"/>
    /// <seealso cref="IsStepComplete"/>
    public bool TryAdvance()
    {
        _logger?.LogDebug(
            "Attempting to advance from step {CurrentStep}. SessionId: {SessionId}",
            CurrentStep, SessionId);

        var nextStep = CurrentStep.GetNextStep();
        if (nextStep == null)
        {
            _logger?.LogDebug(
                "Cannot advance — already at final step {CurrentStep}. SessionId: {SessionId}",
                CurrentStep, SessionId);
            return false;
        }

        if (!IsStepComplete(CurrentStep))
        {
            _logger?.LogDebug(
                "Cannot advance — step {CurrentStep} is not complete. SessionId: {SessionId}",
                CurrentStep, SessionId);
            return false;
        }

        var previousStep = CurrentStep;
        CurrentStep = nextStep.Value;
        LastModifiedAt = DateTime.UtcNow;

        _logger?.LogDebug(
            "Creation state advanced from {FromStep} to {ToStep}. SessionId: {SessionId}",
            previousStep, CurrentStep, SessionId);

        return true;
    }

    /// <summary>
    /// Goes back to the previous step if allowed.
    /// </summary>
    /// <returns>
    /// <c>true</c> if the state moved to the previous step; <c>false</c> if
    /// the current step is the first step (Lineage) and cannot go further back.
    /// </returns>
    /// <remarks>
    /// <para>
    /// All existing selections are preserved when navigating backward. The player
    /// can modify a previous selection and then advance forward again without
    /// losing later selections.
    /// </para>
    /// <para>
    /// Returns <c>false</c> when called from Step 1 (Lineage), which has no
    /// preceding step.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// var state = CharacterCreationState.Create();
    /// state.CurrentStep = CharacterCreationStep.Background;
    /// bool wentBack = state.TryGoBack(); // true — returns to Lineage
    /// // All existing selections preserved
    /// </code>
    /// </example>
    /// <seealso cref="TryAdvance"/>
    public bool TryGoBack()
    {
        _logger?.LogDebug(
            "Attempting to go back from step {CurrentStep}. SessionId: {SessionId}",
            CurrentStep, SessionId);

        var previousStep = CurrentStep.GetPreviousStep();
        if (previousStep == null)
        {
            _logger?.LogDebug(
                "Cannot go back — already at first step {CurrentStep}. SessionId: {SessionId}",
                CurrentStep, SessionId);
            return false;
        }

        var fromStep = CurrentStep;
        CurrentStep = previousStep.Value;
        LastModifiedAt = DateTime.UtcNow;

        _logger?.LogDebug(
            "Creation state went back from {FromStep} to {ToStep}. SessionId: {SessionId}",
            fromStep, CurrentStep, SessionId);

        return true;
    }

    /// <summary>
    /// Determines if the specified step has all required selections.
    /// </summary>
    /// <param name="step">The step to check.</param>
    /// <returns>
    /// <c>true</c> if the step's requirements are satisfied; <c>false</c> otherwise.
    /// </returns>
    /// <remarks>
    /// <para>
    /// Validation rules per step:
    /// </para>
    /// <list type="bullet">
    ///   <item>
    ///     <description>
    ///       Lineage: <see cref="SelectedLineage"/> must have a value. If Clan-Born,
    ///       <see cref="FlexibleAttributeBonus"/> must also have a value.
    ///     </description>
    ///   </item>
    ///   <item><description>Background: <see cref="SelectedBackground"/> must have a value.</description></item>
    ///   <item>
    ///     <description>
    ///       Attributes: <see cref="Attributes"/> must have a value and its
    ///       <c>IsComplete</c> property must be <c>true</c> (all points allocated).
    ///     </description>
    ///   </item>
    ///   <item><description>Archetype: <see cref="SelectedArchetype"/> must have a value.</description></item>
    ///   <item><description>Specialization: <see cref="SelectedSpecialization"/> must have a value.</description></item>
    ///   <item><description>Summary: <see cref="CharacterName"/> must be a non-whitespace string.</description></item>
    /// </list>
    /// </remarks>
    /// <example>
    /// <code>
    /// var state = CharacterCreationState.Create();
    /// state.SelectedLineage = Lineage.IronBlooded;
    /// bool complete = state.IsStepComplete(CharacterCreationStep.Lineage); // true
    /// </code>
    /// </example>
    public bool IsStepComplete(CharacterCreationStep step) => step switch
    {
        CharacterCreationStep.Lineage => SelectedLineage.HasValue &&
            (SelectedLineage != Lineage.ClanBorn || FlexibleAttributeBonus.HasValue),
        CharacterCreationStep.Background => SelectedBackground.HasValue,
        CharacterCreationStep.Attributes => Attributes.HasValue && Attributes.Value.IsComplete,
        CharacterCreationStep.Archetype => SelectedArchetype.HasValue,
        CharacterCreationStep.Specialization => SelectedSpecialization.HasValue,
        CharacterCreationStep.Summary => !string.IsNullOrWhiteSpace(CharacterName),
        _ => false
    };

    /// <summary>
    /// Resets all selections and returns to Step 1.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Clears all step selections, resets the current step to Lineage,
    /// restores the attribute allocation mode to Simple, clears all
    /// validation errors, and updates <see cref="LastModifiedAt"/>.
    /// </para>
    /// <para>
    /// The <see cref="Id"/>, <see cref="SessionId"/>, and <see cref="CreatedAt"/>
    /// are preserved — the session identity remains the same.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// var state = CharacterCreationState.Create();
    /// state.SelectedLineage = Lineage.RuneMarked;
    /// state.CurrentStep = CharacterCreationStep.Background;
    /// state.Reset();
    /// // state.CurrentStep == CharacterCreationStep.Lineage
    /// // state.SelectedLineage == null
    /// </code>
    /// </example>
    public void Reset()
    {
        _logger?.LogDebug(
            "Resetting character creation state. Previous step: {PreviousStep}. SessionId: {SessionId}",
            CurrentStep, SessionId);

        CurrentStep = CharacterCreationStep.Lineage;
        SelectedLineage = null;
        FlexibleAttributeBonus = null;
        SelectedBackground = null;
        AttributeAllocationMode = AttributeAllocationMode.Simple;
        Attributes = null;
        SelectedArchetype = null;
        SelectedSpecialization = null;
        CharacterName = null;
        ValidationErrors.Clear();
        LastModifiedAt = DateTime.UtcNow;

        _logger?.LogInformation(
            "Character creation session reset. SessionId: {SessionId}, CurrentStep: {CurrentStep}",
            SessionId, CurrentStep);
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // DEBUGGING
    // ═══════════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Returns a string representation of the creation state for debugging.
    /// </summary>
    /// <returns>
    /// A formatted string showing the session ID, current step, and all selections.
    /// </returns>
    public override string ToString()
    {
        return $"CharacterCreationState(Session={SessionId}, Step={CurrentStep}, " +
               $"Lineage={SelectedLineage?.ToString() ?? "None"}, " +
               $"Background={SelectedBackground?.ToString() ?? "None"}, " +
               $"Archetype={SelectedArchetype?.ToString() ?? "None"}, " +
               $"Specialization={SelectedSpecialization?.ToString() ?? "None"}, " +
               $"Name={CharacterName ?? "None"}, " +
               $"IsComplete={IsComplete})";
    }
}
