using RuneAndRust.Domain.Enums;

namespace RuneAndRust.Domain.ValueObjects;

/// <summary>
/// Represents the Avatar of Destruction capstone transformation state for a Berserkr character.
/// Tracks damage multipliers, crowd control immunity, movement bonuses, duration,
/// and aftermath conditions.
/// </summary>
/// <remarks>
/// <para>Introduced in v0.20.5c as part of Berserkr Capstone Abilities.</para>
/// <para>Avatar of Destruction is the Berserkr's ultimate transformation:</para>
/// <list type="bullet">
/// <item>Cost: 3 AP + exactly 100 Rage (all Rage consumed)</item>
/// <item>Duration: 2 turns of devastating power</item>
/// <item>All damage dealt is doubled (2.0× multiplier)</item>
/// <item>Immune to all 10 <see cref="CrowdControlType"/> effects</item>
/// <item>+2 movement spaces per turn</item>
/// <item>Always generates +2 Corruption (highest in the game)</item>
/// <item>Causes Exhausted condition (1 turn) when Avatar ends</item>
/// <item>Once per combat encounter</item>
/// </list>
/// <para>Uses <c>private set</c> for <see cref="TurnsRemaining"/> to allow
/// turn-by-turn countdown via <see cref="Tick"/>.</para>
/// </remarks>
public sealed record AvatarState
{
    /// <summary>
    /// Default duration of the Avatar transformation in turns.
    /// </summary>
    public const int DefaultDuration = 2;

    /// <summary>
    /// Default damage multiplier while in Avatar state.
    /// All damage dealt is multiplied by this value.
    /// </summary>
    public const float DefaultDamageMultiplier = 2.0f;

    /// <summary>
    /// Default movement bonus (additional spaces per turn) while in Avatar state.
    /// </summary>
    public const int DefaultMovementBonus = 2;

    /// <summary>
    /// Unique identifier for this transformation instance.
    /// </summary>
    public Guid StateId { get; init; } = Guid.NewGuid();

    /// <summary>
    /// Character undergoing the Avatar of Destruction transformation.
    /// </summary>
    public Guid CharacterId { get; init; }

    /// <summary>
    /// UTC timestamp when the Avatar transformation began.
    /// </summary>
    public DateTime StartedAt { get; init; }

    /// <summary>
    /// Turns remaining in the Avatar state.
    /// Decremented each turn via <see cref="Tick"/>.
    /// Starts at <see cref="DefaultDuration"/> (2).
    /// </summary>
    public int TurnsRemaining { get; private set; } = DefaultDuration;

    /// <summary>
    /// Damage multiplier while in Avatar state (2.0×).
    /// All damage sources are multiplied by this value during the transformation.
    /// </summary>
    public float DamageMultiplier { get; init; } = DefaultDamageMultiplier;

    /// <summary>
    /// Additional movement spaces per turn while in Avatar state (+2).
    /// </summary>
    public int MovementBonus { get; init; } = DefaultMovementBonus;

    /// <summary>
    /// Whether the character is immune to all crowd control effects.
    /// Always true while Avatar is active.
    /// </summary>
    public bool ImmuneToCrowdControl { get; init; } = true;

    /// <summary>
    /// List of specific crowd control types this transformation grants immunity to.
    /// Includes all 10 defined <see cref="CrowdControlType"/> values.
    /// </summary>
    public IReadOnlyList<CrowdControlType> CCImmunityList { get; init; }
        = new[]
        {
            CrowdControlType.Stun,
            CrowdControlType.Root,
            CrowdControlType.Fear,
            CrowdControlType.Charm,
            CrowdControlType.Paralyze,
            CrowdControlType.Slow,
            CrowdControlType.Prone,
            CrowdControlType.ForcedMovement,
            CrowdControlType.Sleep,
            CrowdControlType.Confusion
        };

    /// <summary>
    /// Corruption generated by activating Avatar of Destruction (+2).
    /// This is the highest Corruption cost of any ability in the game.
    /// </summary>
    public int CorruptionGenerated { get; init; } = 2;

    /// <summary>
    /// Whether the Avatar transformation will cause the Exhausted condition
    /// when it ends. Always true — the price of ultimate power.
    /// </summary>
    public bool WillCauseExhaustion { get; init; } = true;

    /// <summary>
    /// Creates a new <see cref="AvatarState"/> for the specified character.
    /// The state is initialized with 2 turns remaining and all Avatar effects active.
    /// </summary>
    /// <param name="characterId">The character activating Avatar of Destruction.</param>
    /// <returns>A new transformation state initialized with full duration and effects.</returns>
    public static AvatarState Create(Guid characterId)
    {
        return new AvatarState
        {
            CharacterId = characterId,
            StartedAt = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Decrements the remaining duration by one turn.
    /// Duration cannot go below zero.
    /// </summary>
    public void Tick()
    {
        TurnsRemaining = Math.Max(0, TurnsRemaining - 1);
    }

    /// <summary>
    /// Ends the Avatar transformation early (if needed).
    /// Sets remaining turns to 0, making <see cref="IsActive"/> return false.
    /// </summary>
    public void End()
    {
        TurnsRemaining = 0;
    }

    /// <summary>
    /// Checks if the Avatar transformation is still active (turns remaining greater than zero).
    /// </summary>
    /// <returns>True if the transformation has not yet expired.</returns>
    public bool IsActive() => TurnsRemaining > 0;

    /// <summary>
    /// Gets the current damage multiplier to apply to all damage dealt.
    /// Returns <see cref="DamageMultiplier"/> (2.0×) while active, or 1.0× when expired.
    /// </summary>
    /// <returns>The damage multiplier based on active state.</returns>
    public float GetDamageMultiplier() => IsActive() ? DamageMultiplier : 1.0f;

    /// <summary>
    /// Checks if a specific crowd control type is negated by the Avatar transformation.
    /// Only grants immunity while the transformation is active.
    /// </summary>
    /// <param name="ccType">The crowd control type to check immunity for.</param>
    /// <returns>True if the Avatar is active and the CC type is in the immunity list.</returns>
    public bool IsImmuneToCC(CrowdControlType ccType)
        => ImmuneToCrowdControl && CCImmunityList.Contains(ccType);

    /// <summary>
    /// Gets a human-readable description of the Avatar transformation state.
    /// </summary>
    /// <returns>
    /// A formatted string showing transformation status, remaining duration,
    /// and active effects.
    /// </returns>
    public string GetDescription()
    {
        if (!IsActive())
            return "Avatar of Destruction: Inactive";

        return $"Avatar of Destruction ({TurnsRemaining} turns): " +
               $"2x damage, CC immune, +{MovementBonus} movement";
    }
}
