namespace RuneAndRust.Domain.ValueObjects;

/// <summary>
/// Represents the outcome of a Fury of the Forlorn cleave attack ability execution.
/// Encapsulates the attack roll, per-target hit/miss breakdown, damage dealt,
/// and Corruption evaluation results.
/// </summary>
/// <remarks>
/// <para>Fury of the Forlorn is the Berserkr's Tier 3 active ability:</para>
/// <list type="bullet">
/// <item>Cost: 3 AP + 30 Rage</item>
/// <item>Requires 80+ Rage to activate</item>
/// <item>Single attack roll compared against each adjacent enemy's Defense individually</item>
/// <item>Single damage roll (weapon + 3d6) applied to all hit targets</item>
/// <item>Corruption: always +1 (requires 80+ Rage to use, so always Enraged)</item>
/// </list>
/// <para>This result object is returned by the ability service to provide
/// complete information for combat log display and state updates.</para>
/// </remarks>
public sealed record FuryCleavesResult
{
    /// <summary>
    /// The attack roll (d20) result before modifiers.
    /// This single roll is compared against each target's Defense individually.
    /// </summary>
    public int AttackRoll { get; init; }

    /// <summary>
    /// IDs of all enemies successfully hit by the cleave attack.
    /// Each hit target takes the full <see cref="DamageDealt"/> amount.
    /// </summary>
    public IReadOnlyList<Guid> TargetsHit { get; init; } = new List<Guid>();

    /// <summary>
    /// IDs of all adjacent enemies whose Defense exceeded the <see cref="AttackRoll"/>.
    /// </summary>
    public IReadOnlyList<Guid> TargetsMissed { get; init; } = new List<Guid>();

    /// <summary>
    /// Damage rolled once for this ability (weapon + 3d6), applied to all hit targets.
    /// </summary>
    public int DamageDealt { get; init; }

    /// <summary>
    /// Total damage across all hit targets (DamageDealt × number of hits).
    /// </summary>
    public int TotalDamageAcrossTargets => DamageDealt * TargetsHit.Count;

    /// <summary>
    /// Amount of Rage spent on this Fury of the Forlorn activation.
    /// Always 30.
    /// </summary>
    public int RageSpent { get; init; } = 30;

    /// <summary>
    /// Whether this Fury of the Forlorn triggered Corruption accumulation.
    /// Always true — the ability requires 80+ Rage and always triggers Corruption.
    /// </summary>
    public bool CorruptionTriggered { get; init; } = true;

    /// <summary>
    /// Corruption amount generated by this ability. Always +1.
    /// </summary>
    public int CorruptionAmount => 1;

    /// <summary>
    /// Gets the number of enemies successfully hit by the cleave.
    /// </summary>
    /// <returns>Count of targets in the <see cref="TargetsHit"/> list.</returns>
    public int GetHitCount() => TargetsHit.Count;

    /// <summary>
    /// Gets the number of enemies that the cleave missed.
    /// </summary>
    /// <returns>Count of targets in the <see cref="TargetsMissed"/> list.</returns>
    public int GetMissCount() => TargetsMissed.Count;

    /// <summary>
    /// Checks if the cleave was effective (hit at least one target).
    /// </summary>
    /// <returns>True if at least one target was hit.</returns>
    public bool WasEffective() => GetHitCount() > 0;

    /// <summary>
    /// Gets a formatted damage breakdown string for combat log display.
    /// </summary>
    /// <returns>
    /// A formatted string showing damage per target and total, e.g.:
    /// "18 × 3 targets = 54 total damage" or "No targets hit".
    /// </returns>
    public string GetDamageBreakdown()
    {
        var hit = GetHitCount();

        return hit > 0
            ? $"{DamageDealt} × {hit} targets = {TotalDamageAcrossTargets} total damage"
            : "No targets hit";
    }

    /// <summary>
    /// Gets a complete result string suitable for combat log display.
    /// </summary>
    /// <returns>A formatted combat log entry for this Fury of the Forlorn attack.</returns>
    public string GetResultString()
    {
        var result = $"Fury of the Forlorn - Attack Roll: {AttackRoll}";

        if (WasEffective())
        {
            result += $" | {GetDamageBreakdown()}";
        }
        else
        {
            result += " | ALL MISSED!";
        }

        if (TargetsMissed.Count > 0)
        {
            result += $" ({GetMissCount()} missed)";
        }

        result += " [+1 CORRUPTION]";

        return result;
    }
}
