// ═══════════════════════════════════════════════════════════════════════════════
// LoreInsightResource.cs
// Immutable value object representing the Lore Insight resource for the
// Jötun-Reader specialization. Manages insight spending, generation from
// discoveries, and rest-based restoration.
// Version: 0.20.3a
// ═══════════════════════════════════════════════════════════════════════════════

namespace RuneAndRust.Domain.ValueObjects;

using RuneAndRust.Domain.Enums;

/// <summary>
/// Represents the Lore Insight resource for the Jötun-Reader specialization.
/// </summary>
/// <remarks>
/// <para>
/// Lore Insight represents accumulated knowledge gained through examination
/// and discovery. The resource has a maximum of 10 points by default, starts
/// fully charged, and restores to maximum on long rest.
/// </para>
/// <para>
/// Insight is generated by:
/// </para>
/// <list type="bullet">
///   <item><description>Examining Jötun machinery or terminals (+1)</description></item>
///   <item><description>Examining Dvergr artifacts or ancient texts (+1)</description></item>
///   <item><description>Exploring new ruins or identifying lore objects (+2)</description></item>
///   <item><description>Deep Scan Master-level success (+2 instead of +1)</description></item>
///   <item><description>Significant or critical discoveries (+1 or +2 bonus)</description></item>
/// </list>
/// <para>
/// This is an immutable value object — all mutation methods return new instances
/// via <c>with</c>-expressions. The original instance is never modified.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var insight = LoreInsightResource.CreateDefault();
/// var (success, remaining) = insight.TrySpend(2);
/// // success = true, remaining.CurrentInsight = 8
/// var afterDiscovery = remaining.GenerateFromDiscovery(DiscoveryType.JotunMachinery);
/// // afterDiscovery.CurrentInsight = 9, afterDiscovery.DiscoveryCount = 1
/// </code>
/// </example>
public sealed record LoreInsightResource
{
    /// <summary>
    /// Default maximum number of Lore Insight points.
    /// </summary>
    public const int DefaultMaxInsight = 10;

    /// <summary>
    /// Gets the current number of Lore Insight points available.
    /// </summary>
    public int CurrentInsight { get; init; }

    /// <summary>
    /// Gets the maximum number of Lore Insight points this resource can hold.
    /// </summary>
    public int MaxInsight { get; init; }

    /// <summary>
    /// Gets the timestamp of the last generation or restoration event, if any.
    /// </summary>
    public DateTime? LastGeneratedAt { get; init; }

    /// <summary>
    /// Gets the total number of discoveries made that generated insight.
    /// </summary>
    public int DiscoveryCount { get; init; }

    /// <summary>
    /// Gets whether any insight points are available to spend.
    /// </summary>
    public bool HasInsight => CurrentInsight > 0;

    /// <summary>
    /// Gets whether insight is at maximum capacity.
    /// </summary>
    public bool IsFullyCharged => CurrentInsight >= MaxInsight;

    /// <summary>
    /// Creates a default LoreInsightResource at full capacity (10/10).
    /// </summary>
    /// <returns>A new resource initialized to default values.</returns>
    public static LoreInsightResource CreateDefault() => new()
    {
        CurrentInsight = DefaultMaxInsight,
        MaxInsight = DefaultMaxInsight,
        LastGeneratedAt = null,
        DiscoveryCount = 0
    };

    /// <summary>
    /// Creates a LoreInsightResource with custom max insight at full capacity.
    /// </summary>
    /// <param name="maxInsight">Maximum insight capacity. Must be positive.</param>
    /// <returns>A new resource initialized to the specified max.</returns>
    public static LoreInsightResource Create(int maxInsight)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(maxInsight, 1);
        return new LoreInsightResource
        {
            CurrentInsight = maxInsight,
            MaxInsight = maxInsight,
            LastGeneratedAt = null,
            DiscoveryCount = 0
        };
    }

    /// <summary>
    /// Attempts to spend the specified amount of Lore Insight.
    /// </summary>
    /// <param name="amount">Number of insight points to spend. Must be positive.</param>
    /// <returns>
    /// A tuple of (success, newResource). If successful, returns the updated resource.
    /// If insufficient insight, returns (false, this) unchanged.
    /// </returns>
    public (bool Success, LoreInsightResource Resource) TrySpend(int amount)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(amount);

        if (CurrentInsight < amount)
            return (false, this);

        return (true, this with { CurrentInsight = CurrentInsight - amount });
    }

    /// <summary>
    /// Determines if spending the specified amount would succeed.
    /// </summary>
    /// <param name="amount">Number of insight points to check. Must be non-negative.</param>
    /// <returns><c>true</c> if sufficient insight is available; otherwise, <c>false</c>.</returns>
    public bool CanSpend(int amount) => amount >= 0 && CurrentInsight >= amount;

    /// <summary>
    /// Generates Lore Insight from a specific discovery type.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Base insight amounts by discovery type:
    /// </para>
    /// <list type="bullet">
    ///   <item><description><b>JotunMachinery, DvergrArtifact, AncientText, Terminal:</b> +1</description></item>
    ///   <item><description><b>Ruin, LoreObject:</b> +2</description></item>
    /// </list>
    /// <para>
    /// Significant discoveries add +1 bonus; critical discoveries add +1 bonus
    /// (stacks with significant for a maximum +2 bonus).
    /// </para>
    /// </remarks>
    /// <param name="discoveryType">The type of discovery made.</param>
    /// <param name="isSignificant">Whether this is a significant discovery (+1 bonus).</param>
    /// <param name="isCritical">Whether this is a critical discovery (+1 bonus).</param>
    /// <returns>A new resource with generated insight, capped at <see cref="MaxInsight"/>.</returns>
    public LoreInsightResource GenerateFromDiscovery(
        LoreDiscoveryType discoveryType,
        bool isSignificant = false,
        bool isCritical = false)
    {
        var baseAmount = discoveryType switch
        {
            LoreDiscoveryType.JotunMachinery => 1,
            LoreDiscoveryType.DvergrArtifact => 1,
            LoreDiscoveryType.AncientText => 1,
            LoreDiscoveryType.Terminal => 1,
            LoreDiscoveryType.Ruin => 2,
            LoreDiscoveryType.LoreObject => 2,
            _ => 1
        };

        var totalAmount = baseAmount;
        if (isSignificant) totalAmount += 1;
        if (isCritical) totalAmount += 1;

        var newInsight = Math.Min(CurrentInsight + totalAmount, MaxInsight);
        return this with
        {
            CurrentInsight = newInsight,
            LastGeneratedAt = DateTime.UtcNow,
            DiscoveryCount = DiscoveryCount + 1
        };
    }

    /// <summary>
    /// Generates a specific amount of Lore Insight (e.g., from Deep Scan success).
    /// </summary>
    /// <param name="amount">Number of insight points to generate. Must be positive.</param>
    /// <returns>A new resource with generated insight, capped at <see cref="MaxInsight"/>.</returns>
    public LoreInsightResource Generate(int amount)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(amount);

        var newInsight = Math.Min(CurrentInsight + amount, MaxInsight);
        return this with
        {
            CurrentInsight = newInsight,
            LastGeneratedAt = DateTime.UtcNow,
            DiscoveryCount = DiscoveryCount + 1
        };
    }

    /// <summary>
    /// Restores the specified number of insight points, capped at <see cref="MaxInsight"/>.
    /// Typically used for short rest partial restoration.
    /// </summary>
    /// <param name="amount">Number of insight points to restore. Must be positive.</param>
    /// <returns>A new resource with insight restored.</returns>
    public LoreInsightResource Restore(int amount)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(amount);

        var newInsight = Math.Min(CurrentInsight + amount, MaxInsight);
        return this with
        {
            CurrentInsight = newInsight,
            LastGeneratedAt = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Fully restores insight to <see cref="MaxInsight"/>.
    /// Typically called after long rest completion.
    /// </summary>
    /// <returns>A new resource at full capacity.</returns>
    public LoreInsightResource RestoreAll() => this with
    {
        CurrentInsight = MaxInsight,
        LastGeneratedAt = DateTime.UtcNow
    };

    /// <summary>
    /// Gets the current Lore Insight value formatted as a display string.
    /// </summary>
    /// <returns>Formatted string (e.g., "7/10").</returns>
    public string GetFormattedValue() => $"{CurrentInsight}/{MaxInsight}";

    /// <summary>
    /// Calculates percentage of maximum Lore Insight.
    /// </summary>
    /// <returns>Integer percentage (0–100).</returns>
    public int GetPercentage() => MaxInsight > 0
        ? (int)Math.Round((decimal)CurrentInsight / MaxInsight * 100)
        : 0;

    /// <summary>
    /// Returns a human-readable representation of the insight state.
    /// </summary>
    public override string ToString() => $"Lore Insight: {CurrentInsight}/{MaxInsight}";
}
