// ═══════════════════════════════════════════════════════════════════════════════
// LoreRevelation.cs
// Value object representing bonus lore revealed by the Ancient Knowledge ability.
// Version: 0.20.3c
// ═══════════════════════════════════════════════════════════════════════════════

namespace RuneAndRust.Domain.ValueObjects;

using RuneAndRust.Domain.Enums;

/// <summary>
/// Bonus lore revealed by the Ancient Knowledge passive ability.
/// </summary>
/// <remarks>
/// <para>
/// Each revelation represents a piece of hidden knowledge discovered during
/// a successful examination. Revelations can reference related locations,
/// historical figures, and generate quest hooks for further exploration.
/// </para>
/// <para>
/// Each revelation generates 1 Lore Insight by default.
/// </para>
/// </remarks>
/// <seealso cref="LoreType"/>
/// <seealso cref="JotunReaderAbilityId"/>
public sealed record LoreRevelation
{
    /// <summary>Unique identifier for this revelation.</summary>
    public Guid RevelationId { get; init; }

    /// <summary>ID of the examination that triggered this.</summary>
    public Guid SourceExaminationId { get; init; }

    /// <summary>Type of lore revealed.</summary>
    public LoreRevelationType RevelationType { get; init; }

    /// <summary>Title/summary of the revelation.</summary>
    public string Title { get; init; } = string.Empty;

    /// <summary>Full revelation content.</summary>
    public string Content { get; init; } = string.Empty;

    /// <summary>Related locations mentioned.</summary>
    public IReadOnlyList<Guid> RelatedLocationIds { get; init; } = new List<Guid>();

    /// <summary>Related figures/people mentioned.</summary>
    public IReadOnlyList<string> RelatedFigures { get; init; } = new List<string>();

    /// <summary>Lore Insight generated by this revelation.</summary>
    public int InsightGenerated { get; init; } = 1;

    /// <summary>When the revelation was made.</summary>
    public DateTime RevealedAt { get; init; }

    /// <summary>
    /// Creates a new lore revelation.
    /// </summary>
    /// <param name="sourceExaminationId">ID of the triggering examination.</param>
    /// <param name="type">Type of lore being revealed.</param>
    /// <param name="title">Summary title for the revelation.</param>
    /// <param name="content">Full content of the revelation.</param>
    /// <param name="relatedLocations">Optional related location IDs.</param>
    /// <param name="relatedFigures">Optional related historical figure names.</param>
    /// <returns>A new <see cref="LoreRevelation"/> instance.</returns>
    public static LoreRevelation Create(
        Guid sourceExaminationId,
        LoreRevelationType type,
        string title,
        string content,
        IEnumerable<Guid>? relatedLocations = null,
        IEnumerable<string>? relatedFigures = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title);
        ArgumentException.ThrowIfNullOrWhiteSpace(content);

        return new LoreRevelation
        {
            RevelationId = Guid.NewGuid(),
            SourceExaminationId = sourceExaminationId,
            RevelationType = type,
            Title = title,
            Content = content,
            RelatedLocationIds = relatedLocations?.ToList().AsReadOnly()
                ?? new List<Guid>().AsReadOnly(),
            RelatedFigures = relatedFigures?.ToList().AsReadOnly()
                ?? new List<string>().AsReadOnly(),
            RevealedAt = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Gets a summary of the revelation.
    /// </summary>
    /// <returns>A formatted summary string.</returns>
    public string GetSummary() => $"{RevelationType}: {Title}";

    /// <summary>
    /// Determines if this revelation has related locations.
    /// </summary>
    /// <returns><c>true</c> if any related locations exist.</returns>
    public bool HasRelatedLocations() => RelatedLocationIds.Count > 0;

    /// <summary>
    /// Gets quest hooks from this revelation.
    /// </summary>
    /// <returns>A list of actionable quest hook strings.</returns>
    public IReadOnlyList<string> GetQuestHooks()
    {
        var hooks = new List<string>();

        if (HasRelatedLocations())
            hooks.Add($"Investigate {RelatedLocationIds.Count} related locations");

        if (RelatedFigures.Count > 0)
            hooks.Add($"Seek information about: {string.Join(", ", RelatedFigures.Take(2))}");

        if (RevelationType == LoreRevelationType.Warning)
            hooks.Add("Heed the warnings mentioned in this revelation");

        return hooks.AsReadOnly();
    }
}
