// ------------------------------------------------------------------------------
// <copyright file="NegotiationResult.cs" company="Rune &amp; Rust">
//     Copyright (c) Rune &amp; Rust. All rights reserved.
// </copyright>
// <summary>
// Represents the complete outcome of a negotiation, either after completion
// or after a single round, including deal terms, position history, and costs.
// Part of v0.15.3e Negotiation System implementation.
// </summary>
// ------------------------------------------------------------------------------

namespace RuneAndRust.Domain.ValueObjects;

using RuneAndRust.Domain.Entities;
using RuneAndRust.Domain.Enums;
using RuneAndRust.Domain.Extensions;

/// <summary>
/// Represents the complete outcome of a negotiation session.
/// </summary>
/// <remarks>
/// <para>
/// The negotiation result captures the full history and outcomes of a
/// multi-round negotiation, including:
/// </para>
/// <list type="bullet">
///   <item><description>Final status (DealReached or Collapsed)</description></item>
///   <item><description>Final positions of both parties</description></item>
///   <item><description>Complete round-by-round history</description></item>
///   <item><description>Total costs (stress, reputation, disposition)</description></item>
///   <item><description>Unlocked dialogue options (if successful)</description></item>
///   <item><description>Deal terms (if successful)</description></item>
///   <item><description>Fumble consequence (if collapsed from fumble)</description></item>
/// </list>
/// <para>
/// This value object is generated by the NegotiationService when a negotiation
/// reaches a terminal state (DealReached or Collapsed).
/// </para>
/// </remarks>
public sealed record NegotiationResult
{
    /// <summary>
    /// Gets the base social result containing standard interaction outcome data.
    /// </summary>
    /// <remarks>
    /// Contains disposition changes, reputation changes, and other standard
    /// social interaction outcome information.
    /// </remarks>
    public required SocialResult BaseResult { get; init; }

    /// <summary>
    /// Gets the overall outcome of the negotiation.
    /// </summary>
    /// <remarks>
    /// <para>
    /// For completed negotiations:
    /// </para>
    /// <list type="bullet">
    ///   <item><description>CriticalSuccess: Deal reached with major concessions from NPC</description></item>
    ///   <item><description>FullSuccess: Deal reached with favorable terms</description></item>
    ///   <item><description>MarginalSuccess: Deal reached with mixed terms</description></item>
    ///   <item><description>Failure: Negotiation collapsed without deal</description></item>
    ///   <item><description>CriticalFailure: Negotiation collapsed from fumble with severe consequences</description></item>
    /// </list>
    /// </remarks>
    public required SkillOutcome Outcome { get; init; }

    /// <summary>
    /// Gets the final negotiation status.
    /// </summary>
    /// <remarks>
    /// Terminal states only: DealReached or Collapsed.
    /// </remarks>
    public required NegotiationStatus FinalStatus { get; init; }

    /// <summary>
    /// Gets the description of the final deal terms, if successful.
    /// </summary>
    /// <remarks>
    /// Only populated when <see cref="FinalStatus"/> is <see cref="NegotiationStatus.DealReached"/>.
    /// Describes what was agreed upon and at what terms.
    /// </remarks>
    public string? FinalDealTerms { get; init; }

    /// <summary>
    /// Gets the final PC position on the 0-8 track.
    /// </summary>
    /// <remarks>
    /// The final position determines the favorability of the deal terms.
    /// Lower values are more favorable to the PC.
    /// </remarks>
    public required int FinalPcPosition { get; init; }

    /// <summary>
    /// Gets the final NPC position on the 0-8 track.
    /// </summary>
    /// <remarks>
    /// The final position determines the NPC's satisfaction with the deal.
    /// </remarks>
    public required int FinalNpcPosition { get; init; }

    /// <summary>
    /// Gets the number of rounds used in the negotiation.
    /// </summary>
    public required int RoundsUsed { get; init; }

    /// <summary>
    /// Gets the total disposition change over the negotiation.
    /// </summary>
    /// <remarks>
    /// Accumulated from all rounds. Can be positive or negative.
    /// Successful negotiations typically result in neutral or positive changes.
    /// Failed negotiations often result in negative changes.
    /// </remarks>
    public required int DispositionChange { get; init; }

    /// <summary>
    /// Gets the total reputation change over the negotiation.
    /// </summary>
    /// <remarks>
    /// Primarily affected by use of the Pressure (Intimidation) tactic,
    /// which always costs reputation due to the Cost of Fear.
    /// </remarks>
    public required int ReputationChange { get; init; }

    /// <summary>
    /// Gets the total stress incurred during negotiation.
    /// </summary>
    /// <remarks>
    /// Primarily from the Deceive tactic, which incurs Psychic Stress
    /// due to the Liar's Burden mechanic.
    /// </remarks>
    public required int TotalStressCost { get; init; }

    /// <summary>
    /// Gets the dialogue options unlocked by successful negotiation.
    /// </summary>
    /// <remarks>
    /// Only populated when <see cref="FinalStatus"/> is <see cref="NegotiationStatus.DealReached"/>.
    /// May include quest options, information, or cooperation agreements.
    /// </remarks>
    public required IReadOnlyList<string> UnlockedOptions { get; init; }

    /// <summary>
    /// Gets the complete history of all negotiation rounds.
    /// </summary>
    /// <remarks>
    /// Contains the full record of tactics used, outcomes, and position
    /// movements for each round of the negotiation.
    /// </remarks>
    public required IReadOnlyList<NegotiationRound> History { get; init; }

    /// <summary>
    /// Gets the fumble consequence if negotiation collapsed from a fumble.
    /// </summary>
    /// <remarks>
    /// Only populated when the negotiation collapsed due to a CriticalFailure.
    /// Contains the lasting consequence of the fumble.
    /// </remarks>
    public FumbleConsequence? FumbleConsequence { get; init; }

    /// <summary>
    /// Gets a value indicating whether the negotiation was successful.
    /// </summary>
    public bool IsSuccess => FinalStatus == NegotiationStatus.DealReached;

    /// <summary>
    /// Gets a value indicating whether the negotiation failed.
    /// </summary>
    public bool IsFailure => FinalStatus == NegotiationStatus.Collapsed;

    /// <summary>
    /// Gets a value indicating whether the negotiation collapsed from a fumble.
    /// </summary>
    public bool IsCollapsedFromFumble => IsFailure && FumbleConsequence != null;

    /// <summary>
    /// Gets a value indicating whether the negotiation has a deal.
    /// </summary>
    public bool HasDeal => IsSuccess && !string.IsNullOrWhiteSpace(FinalDealTerms);

    /// <summary>
    /// Gets the quality of the deal based on final positions.
    /// </summary>
    /// <remarks>
    /// Only meaningful when <see cref="IsSuccess"/> is true.
    /// </remarks>
    public string DealQuality
    {
        get
        {
            if (!IsSuccess)
            {
                return "No deal";
            }

            return FinalPcPosition switch
            {
                <= 2 => "Excellent (strongly favorable to PC)",
                <= 4 => "Good (favorable to PC)",
                5 => "Fair (balanced compromise)",
                <= 6 => "Acceptable (slightly unfavorable)",
                _ => "Poor (unfavorable to PC)"
            };
        }
    }

    /// <summary>
    /// Gets a narrative summary of the negotiation outcome.
    /// </summary>
    /// <returns>A paragraph describing what happened.</returns>
    public string GetNarrativeSummary()
    {
        if (IsSuccess)
        {
            var quality = DealQuality;
            var terms = !string.IsNullOrWhiteSpace(FinalDealTerms)
                ? $" {FinalDealTerms}"
                : "";

            return $"After {RoundsUsed} rounds of negotiation, a deal was reached.{terms} " +
                   $"The outcome was {quality.ToLower()}.";
        }
        else if (IsCollapsedFromFumble)
        {
            return $"After {RoundsUsed} rounds, the negotiation collapsed catastrophically. " +
                   $"A critical misstep has left lasting consequences: {FumbleConsequence!.Description}";
        }
        else
        {
            return $"After {RoundsUsed} rounds, the negotiation collapsed. " +
                   "No deal was possible and the parties parted ways unsuccessfully.";
        }
    }

    /// <summary>
    /// Gets a detailed breakdown of the negotiation for display.
    /// </summary>
    /// <returns>A multi-line summary of the negotiation.</returns>
    public string GetDetailedSummary()
    {
        var lines = new List<string>
        {
            "=== Negotiation Summary ===",
            $"Status: {FinalStatus.GetDisplayName()}",
            $"Outcome: {Outcome}",
            $"Rounds Used: {RoundsUsed}",
            "",
            "Final Positions:",
            $"  PC: {NegotiationPositionTrack.GetPositionName(FinalPcPosition)} ({FinalPcPosition})",
            $"  NPC: {NegotiationPositionTrack.GetPositionName(FinalNpcPosition)} ({FinalNpcPosition})",
            ""
        };

        if (IsSuccess)
        {
            lines.Add($"Deal Quality: {DealQuality}");
            if (!string.IsNullOrWhiteSpace(FinalDealTerms))
            {
                lines.Add($"Terms: {FinalDealTerms}");
            }

            if (UnlockedOptions.Count > 0)
            {
                lines.Add("Unlocked Options:");
                foreach (var option in UnlockedOptions)
                {
                    lines.Add($"  - {option}");
                }
            }
        }
        else
        {
            lines.Add("Result: No deal reached");
            if (FumbleConsequence != null)
            {
                lines.Add($"Consequence: {FumbleConsequence.Description}");
            }
        }

        lines.Add("");
        lines.Add("Costs Incurred:");
        if (TotalStressCost > 0)
        {
            lines.Add($"  Psychic Stress: +{TotalStressCost}");
        }

        if (ReputationChange != 0)
        {
            lines.Add($"  Reputation: {ReputationChange:+0;-0}");
        }

        if (DispositionChange != 0)
        {
            lines.Add($"  Disposition: {DispositionChange:+0;-0}");
        }

        if (TotalStressCost == 0 && ReputationChange == 0 && DispositionChange == 0)
        {
            lines.Add("  (None)");
        }

        return string.Join(Environment.NewLine, lines);
    }

    /// <summary>
    /// Gets a short summary suitable for logging.
    /// </summary>
    /// <returns>A compact single-line summary.</returns>
    public override string ToString()
    {
        return $"Negotiation {FinalStatus}: {Outcome} after {RoundsUsed} rounds, " +
               $"PC@{FinalPcPosition}/NPC@{FinalNpcPosition}";
    }

    /// <summary>
    /// Creates a successful negotiation result.
    /// </summary>
    /// <param name="baseResult">The base social result.</param>
    /// <param name="finalPcPosition">The final PC position.</param>
    /// <param name="finalNpcPosition">The final NPC position.</param>
    /// <param name="roundsUsed">The number of rounds used.</param>
    /// <param name="history">The round history.</param>
    /// <param name="dealTerms">The agreed deal terms.</param>
    /// <param name="unlockedOptions">Dialogue options unlocked by the deal.</param>
    /// <param name="dispositionChange">Total disposition change.</param>
    /// <param name="reputationChange">Total reputation change.</param>
    /// <param name="stressCost">Total stress cost.</param>
    /// <returns>A new <see cref="NegotiationResult"/> representing success.</returns>
    public static NegotiationResult Success(
        SocialResult baseResult,
        int finalPcPosition,
        int finalNpcPosition,
        int roundsUsed,
        IReadOnlyList<NegotiationRound> history,
        string dealTerms,
        IReadOnlyList<string> unlockedOptions,
        int dispositionChange = 0,
        int reputationChange = 0,
        int stressCost = 0)
    {
        // Determine outcome level based on final position
        var outcome = finalPcPosition switch
        {
            <= 2 => SkillOutcome.CriticalSuccess,
            <= 4 => SkillOutcome.FullSuccess,
            _ => SkillOutcome.MarginalSuccess
        };

        return new NegotiationResult
        {
            BaseResult = baseResult,
            Outcome = outcome,
            FinalStatus = NegotiationStatus.DealReached,
            FinalPcPosition = finalPcPosition,
            FinalNpcPosition = finalNpcPosition,
            RoundsUsed = roundsUsed,
            History = history,
            FinalDealTerms = dealTerms,
            UnlockedOptions = unlockedOptions,
            DispositionChange = dispositionChange,
            ReputationChange = reputationChange,
            TotalStressCost = stressCost,
            FumbleConsequence = null
        };
    }

    /// <summary>
    /// Creates a failed negotiation result (collapsed without fumble).
    /// </summary>
    /// <param name="baseResult">The base social result.</param>
    /// <param name="finalPcPosition">The final PC position.</param>
    /// <param name="finalNpcPosition">The final NPC position.</param>
    /// <param name="roundsUsed">The number of rounds used.</param>
    /// <param name="history">The round history.</param>
    /// <param name="dispositionChange">Total disposition change.</param>
    /// <param name="reputationChange">Total reputation change.</param>
    /// <param name="stressCost">Total stress cost.</param>
    /// <returns>A new <see cref="NegotiationResult"/> representing failure.</returns>
    public static NegotiationResult Failure(
        SocialResult baseResult,
        int finalPcPosition,
        int finalNpcPosition,
        int roundsUsed,
        IReadOnlyList<NegotiationRound> history,
        int dispositionChange = 0,
        int reputationChange = 0,
        int stressCost = 0)
    {
        return new NegotiationResult
        {
            BaseResult = baseResult,
            Outcome = SkillOutcome.Failure,
            FinalStatus = NegotiationStatus.Collapsed,
            FinalPcPosition = finalPcPosition,
            FinalNpcPosition = finalNpcPosition,
            RoundsUsed = roundsUsed,
            History = history,
            FinalDealTerms = null,
            UnlockedOptions = Array.Empty<string>(),
            DispositionChange = dispositionChange,
            ReputationChange = reputationChange,
            TotalStressCost = stressCost,
            FumbleConsequence = null
        };
    }

    /// <summary>
    /// Creates a fumble negotiation result (collapsed from critical failure).
    /// </summary>
    /// <param name="baseResult">The base social result.</param>
    /// <param name="finalPcPosition">The final PC position.</param>
    /// <param name="finalNpcPosition">The final NPC position.</param>
    /// <param name="roundsUsed">The number of rounds used.</param>
    /// <param name="history">The round history.</param>
    /// <param name="fumbleConsequence">The fumble consequence.</param>
    /// <param name="dispositionChange">Total disposition change.</param>
    /// <param name="reputationChange">Total reputation change.</param>
    /// <param name="stressCost">Total stress cost.</param>
    /// <returns>A new <see cref="NegotiationResult"/> representing a fumble.</returns>
    public static NegotiationResult Fumble(
        SocialResult baseResult,
        int finalPcPosition,
        int finalNpcPosition,
        int roundsUsed,
        IReadOnlyList<NegotiationRound> history,
        FumbleConsequence fumbleConsequence,
        int dispositionChange = 0,
        int reputationChange = 0,
        int stressCost = 0)
    {
        return new NegotiationResult
        {
            BaseResult = baseResult,
            Outcome = SkillOutcome.CriticalFailure,
            FinalStatus = NegotiationStatus.Collapsed,
            FinalPcPosition = finalPcPosition,
            FinalNpcPosition = finalNpcPosition,
            RoundsUsed = roundsUsed,
            History = history,
            FinalDealTerms = null,
            UnlockedOptions = Array.Empty<string>(),
            DispositionChange = dispositionChange,
            ReputationChange = reputationChange,
            TotalStressCost = stressCost,
            FumbleConsequence = fumbleConsequence
        };
    }

    /// <summary>
    /// Creates a round result (for intermediate states, not terminal).
    /// </summary>
    /// <param name="baseResult">The base social result.</param>
    /// <param name="currentStatus">The current negotiation status.</param>
    /// <param name="pcPosition">The current PC position.</param>
    /// <param name="npcPosition">The current NPC position.</param>
    /// <param name="roundsUsed">The number of rounds used so far.</param>
    /// <param name="history">The round history so far.</param>
    /// <param name="dispositionChange">Accumulated disposition change.</param>
    /// <param name="reputationChange">Accumulated reputation change.</param>
    /// <param name="stressCost">Accumulated stress cost.</param>
    /// <returns>A new <see cref="NegotiationResult"/> for an intermediate state.</returns>
    public static NegotiationResult InProgress(
        SocialResult baseResult,
        NegotiationStatus currentStatus,
        int pcPosition,
        int npcPosition,
        int roundsUsed,
        IReadOnlyList<NegotiationRound> history,
        int dispositionChange = 0,
        int reputationChange = 0,
        int stressCost = 0)
    {
        // Determine outcome based on most recent round
        var lastRound = history.LastOrDefault();
        var outcome = lastRound?.CheckResult ?? SkillOutcome.MarginalSuccess;

        return new NegotiationResult
        {
            BaseResult = baseResult,
            Outcome = outcome,
            FinalStatus = currentStatus,
            FinalPcPosition = pcPosition,
            FinalNpcPosition = npcPosition,
            RoundsUsed = roundsUsed,
            History = history,
            FinalDealTerms = null,
            UnlockedOptions = Array.Empty<string>(),
            DispositionChange = dispositionChange,
            ReputationChange = reputationChange,
            TotalStressCost = stressCost,
            FumbleConsequence = null
        };
    }
}
