namespace RuneAndRust.Domain.ValueObjects;

/// <summary>
/// Immutable result record from The Perfect Hunt capstone ability execution.
/// Records the automatic critical hit and doubled damage against a marked quarry.
/// </summary>
/// <remarks>
/// <para>Introduced in v0.20.7c as the Veiðimaðr Capstone (Ultimate) ability result.</para>
/// <para>The Perfect Hunt declares an unstoppable strike against a marked Quarry:</para>
/// <list type="bullet">
/// <item><description>Automatic critical hit — no attack roll needed (always hits)</description></item>
/// <item><description>All base damage is doubled (base damage × 2)</description></item>
/// <item><description>Costs 3 AP, consumes 1 Quarry Mark</description></item>
/// <item><description>Usable once per long rest (8-hour cooldown)</description></item>
/// </list>
/// <para>Key computed properties:</para>
/// <list type="bullet">
/// <item><description><see cref="IsCriticalHit"/>: Always true (automatic critical)</description></item>
/// <item><description><see cref="CriticalMultiplier"/>: Always 2 (double damage)</description></item>
/// <item><description><see cref="TotalDamage"/>: <see cref="BaseDamageRoll"/> × 2</description></item>
/// </list>
/// <para>The Perfect Hunt represents the culmination of the Veiðimaðr's hunting mastery —
/// the single perfect moment where patience, skill, and precision converge into
/// an unstoppable strike. It is the narrative payoff of the entire specialization.</para>
/// <para>No Corruption risk — The Perfect Hunt follows the Coherent path.</para>
/// </remarks>
public sealed record PerfectHuntResult
{
    /// <summary>
    /// Default critical multiplier for The Perfect Hunt (doubles all damage).
    /// </summary>
    private const int DefaultCriticalMultiplier = 2;

    /// <summary>
    /// Unique identifier of the Veiðimaðr executing the capstone.
    /// </summary>
    public Guid HunterId { get; init; }

    /// <summary>
    /// Unique identifier of the marked quarry targeted by The Perfect Hunt.
    /// </summary>
    public Guid TargetId { get; init; }

    /// <summary>
    /// Display name of the target (for UI, logging, and narrative).
    /// </summary>
    public string TargetName { get; init; } = string.Empty;

    /// <summary>
    /// Base weapon damage roll before critical multiplication.
    /// This is the pre-rolled damage from the hunter's weapon (passed by the caller).
    /// </summary>
    public int BaseDamageRoll { get; init; }

    /// <summary>
    /// Critical damage multiplier. Always 2 for The Perfect Hunt.
    /// Only the base damage dice are doubled — static modifiers are applied separately.
    /// </summary>
    public int CriticalMultiplier => DefaultCriticalMultiplier;

    /// <summary>
    /// Total damage after critical multiplication.
    /// Computed as <see cref="BaseDamageRoll"/> × <see cref="CriticalMultiplier"/>.
    /// </summary>
    public int TotalDamage => BaseDamageRoll * DefaultCriticalMultiplier;

    /// <summary>
    /// Whether this attack is a critical hit. Always true for The Perfect Hunt.
    /// </summary>
    public bool IsCriticalHit => true;

    /// <summary>
    /// Whether a Quarry Mark was consumed by this ability.
    /// Always true for a successful Perfect Hunt execution.
    /// </summary>
    public bool MarkConsumed { get; init; }

    /// <summary>
    /// Whether the capstone resource (once per long rest) was consumed.
    /// Always true for a successful Perfect Hunt execution.
    /// </summary>
    public bool CapstoneUsed { get; init; }

    /// <summary>
    /// Narrative description of the perfect hunt moment.
    /// Generated by the service based on damage dealt and target context.
    /// </summary>
    public string NarrativeDescription { get; init; } = string.Empty;

    /// <summary>
    /// Returns a human-readable description of The Perfect Hunt outcome.
    /// Includes target name, auto-crit confirmation, damage breakdown, and cooldown info.
    /// </summary>
    /// <returns>A narrative description of the capstone result.</returns>
    public string GetDescription()
    {
        return $"THE PERFECT HUNT: {TargetName} struck for {TotalDamage} damage " +
               $"(auto-crit: {BaseDamageRoll} x{CriticalMultiplier}). " +
               "Quarry Mark consumed. Next available: after long rest.";
    }

    /// <summary>
    /// Returns a detailed multi-line breakdown of The Perfect Hunt's effects.
    /// Includes damage calculation, resource consumption, and cooldown information.
    /// </summary>
    /// <returns>A multi-line formatted string showing the complete capstone breakdown.</returns>
    public string GetDamageBreakdown()
    {
        var lines = new List<string>
        {
            "=== THE PERFECT HUNT ===",
            $"Target: {TargetName}",
            $"Base Damage: {BaseDamageRoll}",
            $"Critical Multiplier: x{CriticalMultiplier}",
            $"Total Damage: {TotalDamage}",
            "Auto-Critical: Yes",
            $"Mark Consumed: {(MarkConsumed ? "Yes" : "No")}",
            "Next Available: After long rest",
            "========================"
        };
        return string.Join("\n", lines);
    }

    /// <summary>
    /// Returns a concise status message summarizing The Perfect Hunt.
    /// Suitable for combat log entries and UI notifications.
    /// </summary>
    /// <returns>A formatted status message with damage calculation.</returns>
    public string GetStatusMessage() =>
        $"THE PERFECT HUNT: {TargetName} DEVASTATED! " +
        $"({BaseDamageRoll} x{CriticalMultiplier} = {TotalDamage} damage)";
}
