// ═══════════════════════════════════════════════════════════════════════════════
// RuneChargeResource.cs
// Immutable value object representing the Rune Charge resource for the
// Rúnasmiðr specialization. Manages charge spending, restoration, and
// crafting-based generation.
// Version: 0.20.2a
// ═══════════════════════════════════════════════════════════════════════════════

namespace RuneAndRust.Domain.ValueObjects;

/// <summary>
/// Represents the Rune Charge resource for the Rúnasmiðr specialization.
/// </summary>
/// <remarks>
/// <para>
/// Rune Charges power inscription abilities. The resource has a maximum of 5
/// charges by default, starts fully charged, and restores to maximum on long
/// rest. Crafting generates charges: 1 for standard crafts, 2 for complex crafts.
/// </para>
/// <para>
/// This is an immutable value object — all mutation methods return new instances
/// via <c>with</c>-expressions. The original instance is never modified.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var charges = RuneChargeResource.CreateDefault();
/// var (success, remaining) = charges.TrySpend(1);
/// // success = true, remaining.CurrentCharges = 4
/// var afterCraft = remaining.GenerateFromCraft(isComplexCraft: false);
/// // afterCraft.CurrentCharges = 5 (capped at max)
/// </code>
/// </example>
public sealed record RuneChargeResource
{
    /// <summary>
    /// Default maximum number of Rune Charges.
    /// </summary>
    public const int DefaultMaxCharges = 5;

    /// <summary>
    /// Number of charges generated by a standard crafting action.
    /// </summary>
    public const int StandardCraftGeneration = 1;

    /// <summary>
    /// Number of charges generated by a complex crafting action.
    /// </summary>
    public const int ComplexCraftGeneration = 2;

    /// <summary>
    /// Gets the current number of Rune Charges available.
    /// </summary>
    public int CurrentCharges { get; init; }

    /// <summary>
    /// Gets the maximum number of Rune Charges this resource can hold.
    /// </summary>
    public int MaxCharges { get; init; }

    /// <summary>
    /// Gets the timestamp of the last generation or restoration event, if any.
    /// </summary>
    public DateTime? LastGeneratedAt { get; init; }

    /// <summary>
    /// Gets whether any charges are available to spend.
    /// </summary>
    public bool HasCharges => CurrentCharges > 0;

    /// <summary>
    /// Gets whether charges are at maximum capacity.
    /// </summary>
    public bool IsFullyCharged => CurrentCharges >= MaxCharges;

    /// <summary>
    /// Creates a default RuneChargeResource at full capacity (5/5).
    /// </summary>
    /// <returns>A new resource initialized to default values.</returns>
    public static RuneChargeResource CreateDefault() => new()
    {
        CurrentCharges = DefaultMaxCharges,
        MaxCharges = DefaultMaxCharges,
        LastGeneratedAt = null
    };

    /// <summary>
    /// Creates a RuneChargeResource with custom max charges at full capacity.
    /// </summary>
    /// <param name="maxCharges">Maximum charge capacity. Must be positive.</param>
    /// <returns>A new resource initialized to the specified max.</returns>
    public static RuneChargeResource Create(int maxCharges)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(maxCharges, 1);
        return new RuneChargeResource
        {
            CurrentCharges = maxCharges,
            MaxCharges = maxCharges,
            LastGeneratedAt = null
        };
    }

    /// <summary>
    /// Attempts to spend the specified number of charges.
    /// </summary>
    /// <param name="amount">Number of charges to spend. Must be positive.</param>
    /// <returns>
    /// A tuple of (success, newResource). If successful, returns the updated resource.
    /// If insufficient charges, returns (false, this) unchanged.
    /// </returns>
    public (bool Success, RuneChargeResource Resource) TrySpend(int amount)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(amount);

        if (CurrentCharges < amount)
            return (false, this);

        return (true, this with { CurrentCharges = CurrentCharges - amount });
    }

    /// <summary>
    /// Restores the specified number of charges, capped at <see cref="MaxCharges"/>.
    /// </summary>
    /// <param name="amount">Number of charges to restore. Must be positive.</param>
    /// <returns>A new resource with charges restored.</returns>
    public RuneChargeResource Restore(int amount)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(amount);

        var newCharges = Math.Min(CurrentCharges + amount, MaxCharges);
        return this with
        {
            CurrentCharges = newCharges,
            LastGeneratedAt = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Fully restores charges to <see cref="MaxCharges"/>.
    /// Typically called after long rest completion.
    /// </summary>
    /// <returns>A new resource at full capacity.</returns>
    public RuneChargeResource RestoreAll() => this with
    {
        CurrentCharges = MaxCharges,
        LastGeneratedAt = DateTime.UtcNow
    };

    /// <summary>
    /// Generates charges from a crafting action.
    /// Standard crafts generate 1 charge; complex crafts generate 2 charges.
    /// </summary>
    /// <param name="isComplexCraft">Whether the craft is a complex craft (2 charges) or standard (1 charge).</param>
    /// <returns>A new resource with generated charges, capped at <see cref="MaxCharges"/>.</returns>
    public RuneChargeResource GenerateFromCraft(bool isComplexCraft = false)
    {
        var amount = isComplexCraft ? ComplexCraftGeneration : StandardCraftGeneration;
        var newCharges = Math.Min(CurrentCharges + amount, MaxCharges);
        return this with
        {
            CurrentCharges = newCharges,
            LastGeneratedAt = DateTime.UtcNow
        };
    }

    /// <summary>
    /// Returns a human-readable representation of the charge state.
    /// </summary>
    public override string ToString() => $"Rune Charges: {CurrentCharges}/{MaxCharges}";
}
