using RuneAndRust.Domain.Enums;

namespace RuneAndRust.Domain.ValueObjects;

/// <summary>
/// Represents a single transition zone between two realms with interpolated environmental properties.
/// </summary>
/// <remarks>
/// <para>
/// TransitionZone is an immutable record representing the blended environment that exists
/// at a point between two adjacent realms. The <see cref="BlendFactor"/> determines how
/// much of each realm's properties contribute to the interpolated result.
/// </para>
/// <para>
/// Transition zones are generated by <c>ITransitionZoneGenerator</c> and form sequences
/// that provide gradual environmental shifts between realms:
/// <list type="bullet">
/// <item>Single-zone transition: blend at 50% (midpoint)</item>
/// <item>Two-zone transition: blends at 33% and 66%</item>
/// <item>Three-zone transition: blends at 25%, 50%, and 75%</item>
/// </list>
/// </para>
/// <para>
/// For incompatible realm pairs (e.g., Muspelheim ↔ Niflheim), no transition zones
/// are generated — the generator returns null instead.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // A midpoint transition between Midgard (18°C) and Vanaheim (28°C)
/// var zone = new TransitionZone
/// {
///     FromRealm = RealmId.Midgard,
///     ToRealm = RealmId.Vanaheim,
///     SequenceIndex = 0,
///     BlendFactor = 0.5,
///     InterpolatedProperties = new RealmBiomeProperties { TemperatureCelsius = 23, ... },
///     TransitionTheme = "River ferries upstream... canopy shadows deepen..."
/// };
/// </code>
/// </example>
public sealed record TransitionZone
{
    /// <summary>
    /// Gets the source realm identifier.
    /// </summary>
    /// <remarks>
    /// The realm from which the transition originates. Properties at blend 0.0
    /// are identical to this realm's baseline properties.
    /// </remarks>
    public required RealmId FromRealm { get; init; }

    /// <summary>
    /// Gets the destination realm identifier.
    /// </summary>
    /// <remarks>
    /// The realm toward which the transition progresses. Properties at blend 1.0
    /// are identical to this realm's baseline properties.
    /// </remarks>
    public required RealmId ToRealm { get; init; }

    /// <summary>
    /// Gets the position of this zone within a multi-zone transition sequence (0-based).
    /// </summary>
    /// <remarks>
    /// For single-zone transitions, this value is always 0.
    /// For multi-zone sequences (2-3 zones), values range from 0 to roomCount-1.
    /// Lower indices are closer to the source realm, higher indices closer to the destination.
    /// </remarks>
    public required int SequenceIndex { get; init; }

    /// <summary>
    /// Gets the interpolation blend factor (0.0 = pure source, 1.0 = pure destination).
    /// </summary>
    /// <remarks>
    /// <para>
    /// The blend factor determines the ratio of source-to-destination properties:
    /// <list type="bullet">
    /// <item>0.0 — identical to source realm</item>
    /// <item>0.25 — 75% source, 25% destination</item>
    /// <item>0.5 — equal blend (midpoint)</item>
    /// <item>0.75 — 25% source, 75% destination</item>
    /// <item>1.0 — identical to destination realm</item>
    /// </list>
    /// </para>
    /// </remarks>
    public required double BlendFactor { get; init; }

    /// <summary>
    /// Gets the interpolated environmental properties at this transition point.
    /// </summary>
    /// <remarks>
    /// All six <see cref="RealmBiomeProperties"/> fields are linearly interpolated
    /// using the formula: <c>result = from + (to - from) * blend</c>.
    /// Includes temperature, aetheric intensity, humidity, light level, scale factor,
    /// and corrosion rate.
    /// </remarks>
    public required RealmBiomeProperties InterpolatedProperties { get; init; }

    /// <summary>
    /// Gets the narrative theme description for this transition, if available.
    /// </summary>
    /// <remarks>
    /// Loaded from the adjacency configuration. Describes the atmospheric shift
    /// experienced when traveling between realms.
    /// Example: "River ferries upstream... canopy shadows deepen..."
    /// May be null if no theme is defined for this realm pair.
    /// </remarks>
    public string? TransitionTheme { get; init; }

    /// <summary>
    /// Gets whether this transition zone is at the midpoint between the two realms.
    /// </summary>
    public bool IsMidpoint => Math.Abs(BlendFactor - 0.5) < 0.01;

    /// <summary>
    /// Gets the dominant realm (whichever has more influence at this blend point).
    /// </summary>
    /// <remarks>
    /// Returns <see cref="FromRealm"/> if blend is below 0.5,
    /// <see cref="ToRealm"/> if blend is 0.5 or above.
    /// </remarks>
    public RealmId DominantRealm => BlendFactor >= 0.5 ? ToRealm : FromRealm;

    /// <summary>
    /// Returns a human-readable representation of this transition zone.
    /// </summary>
    public override string ToString() =>
        $"TransitionZone[{FromRealm}→{ToRealm} @{BlendFactor:P0} (index {SequenceIndex})]";
}
