using RuneAndRust.Core;
using Serilog;

namespace RuneAndRust.Engine;

/// <summary>
/// v0.25.1: Service for managing Momentum resource (Strandhogg specialization)
/// Momentum is a 0-100 resource generated by movement (+5) and attacks (+15)
/// Decays slowly out of combat (5 per turn)
/// </summary>
public class MomentumService
{
    private static readonly ILogger _log = Log.ForContext<MomentumService>();

    // Constants for Momentum mechanics
    public const int MAX_MOMENTUM = 100;
    public const int MOMENTUM_PER_MOVE = 5;
    public const int MOMENTUM_PER_HIT = 15;
    public const int MOMENTUM_DECAY_OUT_OF_COMBAT = 5;
    public const int TIDAL_RUSH_BONUS_R1 = 10;
    public const int TIDAL_RUSH_BONUS_R2 = 15;

    /// <summary>
    /// Get current Momentum for a character
    /// </summary>
    public int GetCurrentMomentum(PlayerCharacter character)
    {
        return Math.Clamp(character.Momentum, 0, MAX_MOMENTUM);
    }

    /// <summary>
    /// Generate Momentum from a source (movement, attacks, etc.)
    /// Caps at MAX_MOMENTUM
    /// </summary>
    public void GenerateMomentum(PlayerCharacter character, int amount, string source)
    {
        using (_log.BeginTimedOperation("GenerateMomentum"))
        {
            int currentMomentum = character.Momentum;
            int newMomentum = Math.Clamp(currentMomentum + amount, 0, MAX_MOMENTUM);
            int actualGained = newMomentum - currentMomentum;

            character.Momentum = newMomentum;

            _log.Information(
                "Momentum Generated: Character={CharacterName}, Source={Source}, Amount={Amount}, Actual={Actual}, Total={Total}",
                character.Name, source, amount, actualGained, newMomentum);
        }
    }

    /// <summary>
    /// Spend Momentum on an ability
    /// Returns true if successful, false if insufficient Momentum
    /// </summary>
    public bool SpendMomentum(PlayerCharacter character, int cost, string abilityName)
    {
        if (character.Momentum < cost)
        {
            _log.Warning(
                "Insufficient Momentum: Character={CharacterName}, Ability={Ability}, Cost={Cost}, Have={Have}",
                character.Name, abilityName, cost, character.Momentum);
            return false;
        }

        character.Momentum -= cost;

        _log.Information(
            "Momentum Spent: Character={CharacterName}, Ability={Ability}, Cost={Cost}, Remaining={Remaining}",
            character.Name, abilityName, cost, character.Momentum);

        return true;
    }

    /// <summary>
    /// Apply Momentum decay out of combat
    /// Decays 5 Momentum per turn when not in combat
    /// </summary>
    public void ApplyMomentumDecay(PlayerCharacter character, bool isInCombat)
    {
        if (isInCombat)
        {
            _log.Debug("No Momentum decay: Character={CharacterName} is in combat", character.Name);
            return;
        }

        if (character.Momentum == 0)
        {
            return;
        }

        int previousMomentum = character.Momentum;
        character.Momentum = Math.Max(character.Momentum - MOMENTUM_DECAY_OUT_OF_COMBAT, 0);

        _log.Information(
            "Momentum Decay: Character={CharacterName}, Lost={Lost}, Remaining={Remaining}",
            character.Name, previousMomentum - character.Momentum, character.Momentum);
    }

    /// <summary>
    /// Initialize Momentum at combat start (for Harrier's Alacrity passive)
    /// </summary>
    public void InitializeCombatMomentum(PlayerCharacter character, int abilityRank)
    {
        int startingMomentum = abilityRank >= 3 ? 30 : 20;
        character.Momentum = startingMomentum;

        _log.Information(
            "Combat Momentum Initialized: Character={CharacterName}, Rank={Rank}, Starting={Starting}",
            character.Name, abilityRank, startingMomentum);
    }

    /// <summary>
    /// Calculate Tidal Rush bonus Momentum
    /// Tidal Rush provides bonus Momentum when hitting debuffed enemies
    /// </summary>
    public int CalculateTidalRushBonus(Enemy target, int tidalRushRank)
    {
        if (tidalRushRank == 0)
        {
            return 0;
        }

        // Check for mental/control debuffs
        bool hasDebuff = target.StatusEffects.Any(se =>
            se.EffectType == "Disoriented" ||
            se.EffectType == "Stunned" ||
            se.EffectType == "Feared" ||
            se.EffectType == "Confused" ||
            se.EffectType == "Slowed" ||
            se.EffectType == "Rooted");

        // Rank 3: Also check for DoT effects
        if (tidalRushRank >= 3)
        {
            hasDebuff = hasDebuff || target.StatusEffects.Any(se =>
                se.EffectType == "Bleeding" ||
                se.EffectType == "Burning" ||
                se.EffectType == "Poisoned");
        }

        if (!hasDebuff)
        {
            return 0;
        }

        // Calculate bonus based on rank
        int bonus = tidalRushRank >= 2 ? TIDAL_RUSH_BONUS_R2 : TIDAL_RUSH_BONUS_R1;

        _log.Information(
            "Tidal Rush Bonus: Target={TargetName}, Rank={Rank}, Bonus={Bonus}",
            target.Name, tidalRushRank, bonus);

        return bonus;
    }

    /// <summary>
    /// Check if a target is debuffed (for Vicious Flank damage bonus)
    /// </summary>
    public bool IsTargetDebuffed(Enemy target)
    {
        return target.StatusEffects.Any(se =>
            se.EffectType == "Disoriented" ||
            se.EffectType == "Stunned" ||
            se.EffectType == "Feared" ||
            se.EffectType == "Slowed" ||
            se.EffectType == "Rooted" ||
            se.EffectType == "Bleeding");
    }

    /// <summary>
    /// Get Vigilance bonus from Harrier's Alacrity
    /// </summary>
    public int GetHarriersAlacrityVigilanceBonus(int abilityRank)
    {
        return abilityRank >= 2 ? 3 : 2;
    }
}
