using RuneAndRust.Core;
using Serilog;

namespace RuneAndRust.Engine;

/// <summary>
/// Service for managing Righteous Fervor resource system (v0.19.2 - Iron-Bane specialization)
/// Righteous Fervor is a coherent resource generated by fighting Mechanical/Undying enemies
/// Unlike Savagery, Fervor does not inflict Stress - it's safe and righteous
/// </summary>
public class RighteousFervorService
{
    private static readonly ILogger _log = Log.ForContext<RighteousFervorService>();

    /// <summary>
    /// Check if character has enough Fervor for an ability
    /// </summary>
    public bool HasEnoughFervor(PlayerCharacter character, int required)
    {
        return character.RighteousFervor >= required;
    }

    /// <summary>
    /// Generate Righteous Fervor with logging
    /// Applies Righteous Conviction multipliers if the character has that ability
    /// </summary>
    public void GenerateFervor(PlayerCharacter character, int amount, string source)
    {
        if (amount <= 0)
        {
            _log.Warning("Attempted to generate non-positive Fervor: Character={CharacterName}, Amount={Amount}, Source={Source}",
                character.Name, amount, source);
            return;
        }

        // Apply Righteous Conviction multiplier if character has it
        double multiplier = GetFervorMultiplier(character);
        int actualAmount = (int)(amount * multiplier);

        int oldFervor = character.RighteousFervor;
        character.RighteousFervor = Math.Min(character.RighteousFervor + actualAmount, character.MaxRighteousFervor);
        int actualGained = character.RighteousFervor - oldFervor;

        if (multiplier > 1.0)
        {
            _log.Information("Righteous Fervor generated (with {Multiplier}x multiplier): Character={CharacterName}, Base={BaseAmount}, Actual={ActualAmount}, Source={Source}, NewTotal={NewTotal}/{Max}",
                multiplier, character.Name, amount, actualGained, source, character.RighteousFervor, character.MaxRighteousFervor);
        }
        else
        {
            _log.Information("Righteous Fervor generated: Character={CharacterName}, Amount={Amount}, Source={Source}, NewTotal={NewTotal}/{Max}",
                character.Name, actualGained, source, character.RighteousFervor, character.MaxRighteousFervor);
        }
    }

    /// <summary>
    /// Spend Righteous Fervor if character has enough
    /// </summary>
    public bool SpendFervor(PlayerCharacter character, int amount, string purpose)
    {
        if (amount <= 0)
        {
            _log.Warning("Attempted to spend non-positive Fervor: Character={CharacterName}, Amount={Amount}, Purpose={Purpose}",
                character.Name, amount, purpose);
            return false;
        }

        if (!HasEnoughFervor(character, amount))
        {
            _log.Warning("Insufficient Righteous Fervor: Character={CharacterName}, Required={Required}, Available={Available}, Purpose={Purpose}",
                character.Name, amount, character.RighteousFervor, purpose);
            return false;
        }

        character.RighteousFervor -= amount;

        _log.Information("Righteous Fervor spent: Character={CharacterName}, Amount={Amount}, Purpose={Purpose}, Remaining={Remaining}/{Max}",
            character.Name, amount, purpose, character.RighteousFervor, character.MaxRighteousFervor);

        return true;
    }

    /// <summary>
    /// Get Fervor generation multiplier based on Righteous Conviction ability
    /// </summary>
    private double GetFervorMultiplier(PlayerCharacter character)
    {
        var righteousConviction = character.Abilities
            .FirstOrDefault(a => a.Name == "Righteous Conviction"); // Righteous Conviction ability

        if (righteousConviction == null)
            return 1.0;

        return righteousConviction.CurrentRank switch
        {
            1 => 1.5,  // +50%
            2 => 1.75, // +75%
            3 => 2.0,  // +100% (double)
            _ => 1.0
        };
    }

    /// <summary>
    /// Refund ability costs when defeating Mechanical/Undying (Righteous Conviction Rank 3)
    /// </summary>
    public void RefundAbilityCosts(PlayerCharacter character, int staminaCost, int fervorCost)
    {
        var righteousConviction = character.Abilities
            .FirstOrDefault(a => a.Name == "Righteous Conviction" && a.CurrentRank == 3);

        if (righteousConviction == null)
            return;

        // Rank 3: Defeating Mechanical/Undying refunds 50% ability costs
        int staminaRefund = staminaCost / 2;
        int fervorRefund = fervorCost / 2;

        if (staminaRefund > 0)
        {
            character.Stamina = Math.Min(character.Stamina + staminaRefund, character.MaxStamina);
            _log.Information("Righteous Conviction refunded Stamina: Character={CharacterName}, Amount={Amount}",
                character.Name, staminaRefund);
        }

        if (fervorRefund > 0)
        {
            character.RighteousFervor = Math.Min(character.RighteousFervor + fervorRefund, character.MaxRighteousFervor);
            _log.Information("Righteous Conviction refunded Fervor: Character={CharacterName}, Amount={Amount}",
                character.Name, fervorRefund);
        }
    }

    /// <summary>
    /// Reset Fervor to 0 (typically at combat end or rest)
    /// </summary>
    public void ResetFervor(PlayerCharacter character)
    {
        if (character.RighteousFervor > 0)
        {
            _log.Information("Righteous Fervor reset: Character={CharacterName}, PreviousAmount={Previous}",
                character.Name, character.RighteousFervor);
            character.RighteousFervor = 0;
        }
    }

    /// <summary>
    /// Get formatted Fervor display string
    /// </summary>
    public string GetFervorDisplay(PlayerCharacter character)
    {
        return $"{character.RighteousFervor}/{character.MaxRighteousFervor} Fervor 🔥";
    }
}
