namespace RuneAndRust.Core.Models;

/// <summary>
/// Represents a contextual help tip displayed to the player (v0.3.9c).
/// Generated by ContextHelpService based on current game state.
/// </summary>
/// <param name="Title">Short category label (e.g., "Bleeding", "Hazard", "Tactical").</param>
/// <param name="Message">Actionable tip text with optional Spectre.Console markup.</param>
/// <param name="Priority">Higher values indicate more important tips (10 = Critical, 5 = Tactical, 3 = Info).</param>
/// <param name="Color">Spectre.Console color string for the title (default: "grey").</param>
public record HelpTip(
    string Title,
    string Message,
    int Priority,
    string Color = "grey"
)
{
    /// <summary>
    /// Priority level for critical warnings (stunned, breaking point, imminent death).
    /// </summary>
    public const int PriorityCritical = 10;

    /// <summary>
    /// Priority level for warnings (active hazards, low resources).
    /// </summary>
    public const int PriorityWarning = 8;

    /// <summary>
    /// Priority level for tactical advice (enemy weaknesses, combat suggestions).
    /// </summary>
    public const int PriorityTactical = 5;

    /// <summary>
    /// Priority level for general information (hints, reminders).
    /// </summary>
    public const int PriorityInfo = 3;

    /// <summary>
    /// Creates a critical-priority tip with red color.
    /// </summary>
    public static HelpTip Critical(string title, string message) =>
        new(title, message, PriorityCritical, "red");

    /// <summary>
    /// Creates a warning-priority tip with yellow color.
    /// </summary>
    public static HelpTip Warning(string title, string message) =>
        new(title, message, PriorityWarning, "yellow");

    /// <summary>
    /// Creates a tactical-priority tip with cyan color.
    /// </summary>
    public static HelpTip Tactical(string title, string message) =>
        new(title, message, PriorityTactical, "cyan");

    /// <summary>
    /// Creates an info-priority tip with grey color.
    /// </summary>
    public static HelpTip Info(string title, string message) =>
        new(title, message, PriorityInfo, "grey");
}
