using System.Text;
using Microsoft.Extensions.Logging;
using RuneAndRust.Core.Enums;
using RuneAndRust.Core.Interfaces;
using RuneAndRust.Core.Models;
using RuneAndRust.Core.Models.Analysis;

namespace RuneAndRust.Engine.Services;

/// <summary>
/// Monte Carlo simulation service for validating loot drop rates.
/// Runs batch loot generation and compares actual distributions against expected probabilities.
/// </summary>
public class LootAuditService : ILootAuditService
{
    private readonly ILootService _lootService;
    private readonly ILogger<LootAuditService> _logger;

    /// <summary>
    /// Variance threshold for WARNING severity (1%).
    /// </summary>
    private const double WarningThreshold = 1.0;

    /// <summary>
    /// Variance threshold for CRITICAL severity (5%).
    /// </summary>
    private const double CriticalThreshold = 5.0;

    public LootAuditService(ILootService lootService, ILogger<LootAuditService> logger)
    {
        _lootService = lootService ?? throw new ArgumentNullException(nameof(lootService));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc />
    public async Task<LootAuditReport> RunAuditAsync(LootAuditConfiguration config)
    {
        _logger.LogInformation(
            "Starting Loot Audit: {Iterations} iterations in {Biome} ({DangerLevel})",
            config.Iterations, config.Biome, config.DangerLevel);

        var stats = new LootStatistics();
        var context = new LootGenerationContext(
            config.Biome,
            config.DangerLevel,
            null, // No quality tier override - let it roll naturally
            config.WitsBonus);

        // Sequential execution for thread safety (LootService uses non-thread-safe Random)
        for (int i = 0; i < config.Iterations; i++)
        {
            var result = _lootService.GenerateLoot(context);
            stats.Record(result);

            // Progress logging every 10% for large batches
            if (config.Iterations >= 1000 && (i + 1) % (config.Iterations / 10) == 0)
            {
                _logger.LogDebug(
                    "Audit progress: {Completed}/{Total} iterations ({Percent}%)",
                    i + 1, config.Iterations, (i + 1) * 100 / config.Iterations);
            }
        }

        // Calculate variance flags
        var flags = CalculateVarianceFlags(stats, config);

        // Generate markdown report
        var markdown = GenerateMarkdownReport(stats, config, flags);

        _logger.LogInformation(
            "Loot Audit complete: {Items} items dropped, {Value} total Scrip, {FlagCount} variance flags",
            stats.TotalItemsDropped, stats.TotalScripValue, flags.Count);

        return await Task.FromResult(new LootAuditReport(stats, markdown, flags));
    }

    /// <summary>
    /// Calculates variance flags by comparing actual drop rates to expected values from LootTables.
    /// </summary>
    private List<VarianceFlag> CalculateVarianceFlags(LootStatistics stats, LootAuditConfiguration config)
    {
        var flags = new List<VarianceFlag>();

        // Check quality tier distribution
        var expectedQuality = LootTables.QualityWeightsByDanger.GetValueOrDefault(config.DangerLevel);
        if (expectedQuality != null)
        {
            foreach (var tier in Enum.GetValues<QualityTier>())
            {
                var actual = stats.GetQualityTierPercent(tier);
                var expected = expectedQuality.GetValueOrDefault(tier, 0);
                var severity = ClassifyVariance(Math.Abs(actual - expected));

                flags.Add(new VarianceFlag(
                    "QualityTier",
                    tier.ToString(),
                    actual,
                    expected,
                    severity));
            }
        }

        // Check item type distribution
        var expectedTypes = LootTables.ItemTypeByBiome.GetValueOrDefault(config.Biome);
        if (expectedTypes != null)
        {
            foreach (var type in Enum.GetValues<ItemType>())
            {
                // Skip KeyItem as it's not generated by loot tables
                if (type == ItemType.KeyItem)
                    continue;

                var actual = stats.GetItemTypePercent(type);
                var expected = expectedTypes.GetValueOrDefault(type, 0);
                var severity = ClassifyVariance(Math.Abs(actual - expected));

                flags.Add(new VarianceFlag(
                    "ItemType",
                    type.ToString(),
                    actual,
                    expected,
                    severity));
            }
        }

        return flags;
    }

    /// <summary>
    /// Classifies variance magnitude into severity levels.
    /// </summary>
    private static VarianceSeverity ClassifyVariance(double absoluteVariance)
    {
        if (absoluteVariance > CriticalThreshold)
            return VarianceSeverity.Critical;
        if (absoluteVariance > WarningThreshold)
            return VarianceSeverity.Warning;
        return VarianceSeverity.Ok;
    }

    /// <summary>
    /// Generates a human-readable markdown report from the audit results.
    /// </summary>
    private string GenerateMarkdownReport(
        LootStatistics stats,
        LootAuditConfiguration config,
        List<VarianceFlag> flags)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("# Loot Audit Report");
        sb.AppendLine();
        sb.AppendLine($"**Date:** {DateTime.Now:yyyy-MM-dd HH:mm:ss} | **Iterations:** {stats.TotalIterations:N0}");
        sb.AppendLine($"**Biome:** {config.Biome} | **Danger Level:** {config.DangerLevel}");
        if (config.WitsBonus > 0)
            sb.AppendLine($"**WITS Bonus:** +{config.WitsBonus}");
        sb.AppendLine();

        // Summary Statistics
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"- **Total Items Dropped:** {stats.TotalItemsDropped:N0}");
        sb.AppendLine($"- **Average Items per Iteration:** {stats.AverageItemsPerIteration:F2}");
        sb.AppendLine($"- **Total Scrip Value:** {stats.TotalScripValue:N0}");
        sb.AppendLine($"- **Average Scrip per Iteration:** {stats.AverageScripPerIteration:F2}");
        sb.AppendLine($"- **Success Rate:** {stats.SuccessRate:F1}%");
        sb.AppendLine();

        // Quality Tier Distribution
        sb.AppendLine("## Quality Tier Distribution");
        sb.AppendLine();
        sb.AppendLine("| Tier | Count | Actual % | Expected % | Variance | Status |");
        sb.AppendLine("|------|-------|----------|------------|----------|--------|");

        var qualityFlags = flags.Where(f => f.Category == "QualityTier").ToList();
        foreach (var flag in qualityFlags.OrderBy(f => Enum.Parse<QualityTier>(f.ItemName)))
        {
            var count = stats.QualityTierCounts.GetValueOrDefault(Enum.Parse<QualityTier>(flag.ItemName), 0);
            var variance = flag.Variance >= 0 ? $"+{flag.Variance:F1}%" : $"{flag.Variance:F1}%";
            var status = GetStatusEmoji(flag.Severity);

            sb.AppendLine($"| {flag.ItemName} | {count:N0} | {flag.ActualPercent:F1}% | {flag.ExpectedPercent:F1}% | {variance} | {status} |");
        }
        sb.AppendLine();

        // Item Type Distribution
        sb.AppendLine("## Item Type Distribution");
        sb.AppendLine();
        sb.AppendLine("| Type | Count | Actual % | Expected % | Variance | Status |");
        sb.AppendLine("|------|-------|----------|------------|----------|--------|");

        var typeFlags = flags.Where(f => f.Category == "ItemType").ToList();
        foreach (var flag in typeFlags.OrderBy(f => Enum.Parse<ItemType>(f.ItemName)))
        {
            var count = stats.ItemTypeCounts.GetValueOrDefault(Enum.Parse<ItemType>(flag.ItemName), 0);
            var variance = flag.Variance >= 0 ? $"+{flag.Variance:F1}%" : $"{flag.Variance:F1}%";
            var status = GetStatusEmoji(flag.Severity);

            sb.AppendLine($"| {flag.ItemName} | {count:N0} | {flag.ActualPercent:F1}% | {flag.ExpectedPercent:F1}% | {variance} | {status} |");
        }
        sb.AppendLine();

        // Anomalies Section
        var anomalies = flags.Where(f => f.Severity != VarianceSeverity.Ok).ToList();
        sb.AppendLine("## Anomalies");
        sb.AppendLine();

        if (anomalies.Count == 0)
        {
            sb.AppendLine("*None detected. All distributions are within acceptable bounds.*");
        }
        else
        {
            var criticals = anomalies.Where(f => f.Severity == VarianceSeverity.Critical).ToList();
            var warnings = anomalies.Where(f => f.Severity == VarianceSeverity.Warning).ToList();

            if (criticals.Count > 0)
            {
                sb.AppendLine("### Critical (>5% deviation)");
                sb.AppendLine();
                foreach (var flag in criticals)
                {
                    sb.AppendLine($"- **{flag.Category}:{flag.ItemName}** - Actual {flag.ActualPercent:F1}% vs Expected {flag.ExpectedPercent:F1}% (Variance: {flag.Variance:+0.0;-0.0}%)");
                }
                sb.AppendLine();
            }

            if (warnings.Count > 0)
            {
                sb.AppendLine("### Warnings (1-5% deviation)");
                sb.AppendLine();
                foreach (var flag in warnings)
                {
                    sb.AppendLine($"- **{flag.Category}:{flag.ItemName}** - Actual {flag.ActualPercent:F1}% vs Expected {flag.ExpectedPercent:F1}% (Variance: {flag.Variance:+0.0;-0.0}%)");
                }
                sb.AppendLine();
            }
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"*Generated by LootAuditService v0.3.13a*");

        return sb.ToString();
    }

    /// <summary>
    /// Gets a status indicator string for the given severity level.
    /// </summary>
    private static string GetStatusEmoji(VarianceSeverity severity) => severity switch
    {
        VarianceSeverity.Ok => "OK",
        VarianceSeverity.Warning => "WARN",
        VarianceSeverity.Critical => "CRIT",
        _ => "?"
    };
}
