// ═══════════════════════════════════════════════════════════════════════════════
// JotunReaderTier3AbilityService.cs
// Implements Tier 3 and Capstone ability operations for the Jötun-Reader
// specialization: Lore Keeper, Ancient Knowledge, and Voice of the Giants.
// Version: 0.20.3c
// ═══════════════════════════════════════════════════════════════════════════════

namespace RuneAndRust.Application.Services;

using Microsoft.Extensions.Logging;
using RuneAndRust.Domain.Enums;
using RuneAndRust.Domain.ValueObjects;

/// <summary>
/// Implements Tier 3 and Capstone Jötun-Reader abilities: Lore Keeper,
/// Ancient Knowledge, and Voice of the Giants.
/// </summary>
/// <remarks>
/// <para>
/// This service handles all Tier 3 and Capstone ability operations for the
/// Jötun-Reader specialization. It operates on immutable value objects and
/// returns new instances for all state transitions.
/// </para>
/// <para>
/// <b>Tier 3 requires 16 PP invested in the Jötun-Reader ability tree.</b>
/// Each Tier 3 ability costs 5 PP to unlock.
/// <b>Capstone requires 24 PP invested.</b>
/// The Capstone ability costs 6 PP to unlock.
/// </para>
/// <para>
/// Logging follows the established specialization service pattern:
/// </para>
/// <list type="bullet">
///   <item><description>
///     <b>Information:</b> Successful auto-successes, lore revelations,
///     technology activations, Lore Insight generation
///   </description></item>
///   <item><description>
///     <b>Warning:</b> Rejected operations (already used Voice of the Giants,
///     insufficient PP, non-historical objects)
///   </description></item>
///   <item><description>
///     <b>Debug:</b> Prerequisite checks, layer checks, lore count calculations
///   </description></item>
/// </list>
/// </remarks>
/// <seealso cref="LoreRevelation"/>
/// <seealso cref="ActivatedTechnology"/>
/// <seealso cref="JotunReaderTier2AbilityService"/>
public class JotunReaderTier3AbilityService
{
    private readonly ILogger<JotunReaderTier3AbilityService> _logger;

    // ═══════ Constants ═══════

    /// <summary>
    /// PP threshold required to unlock Tier 3 Jötun-Reader abilities.
    /// </summary>
    public const int Tier3Threshold = 16;

    /// <summary>
    /// PP threshold required to unlock the Capstone Jötun-Reader ability.
    /// </summary>
    public const int CapstoneThreshold = 24;

    /// <summary>
    /// Lore Insight generated by Lore Keeper on first examination of a
    /// historical object.
    /// </summary>
    public const int LoreKeeperFirstExamInsight = 2;

    /// <summary>
    /// Number of bonus lore entries revealed on Expert success.
    /// </summary>
    public const int AncientKnowledgeExpertLoreCount = 1;

    /// <summary>
    /// Number of bonus lore entries revealed on Master success.
    /// </summary>
    public const int AncientKnowledgeMasterLoreCount = 2;

    /// <summary>
    /// Lore Insight generated per bonus lore entry from Ancient Knowledge.
    /// </summary>
    public const int AncientKnowledgeInsightPerLore = 1;

    /// <summary>
    /// AP cost for Voice of the Giants.
    /// </summary>
    public const int VoiceOfTheGiantsAPCost = 5;

    /// <summary>
    /// Lore Insight cost for Voice of the Giants.
    /// </summary>
    public const int VoiceOfTheGiantsInsightCost = 8;

    /// <summary>
    /// Default duration (in minutes) for technology activations.
    /// </summary>
    public const int DefaultActivationDurationMinutes = 60;

    /// <summary>
    /// Layer number that Lore Keeper auto-succeeds for historical objects.
    /// </summary>
    public const int LoreKeeperAutoSucceedLayer = 3;

    /// <summary>
    /// Tag used to identify historical objects for Lore Keeper.
    /// </summary>
    public const string HistoricalTag = "Historical";

    /// <summary>
    /// Initializes a new instance of <see cref="JotunReaderTier3AbilityService"/>.
    /// </summary>
    /// <param name="logger">Logger for ability audit trail.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="logger"/> is null.</exception>
    public JotunReaderTier3AbilityService(
        ILogger<JotunReaderTier3AbilityService> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    // ═══════ Lore Keeper (Passive) ═══════

    /// <summary>
    /// Determines whether the given object tags indicate a historical object
    /// eligible for Lore Keeper auto-success.
    /// </summary>
    /// <param name="objectTags">Tags associated with the object being examined.</param>
    /// <returns><c>true</c> if the object is categorized as historical.</returns>
    public bool IsHistoricalObject(IReadOnlyList<string> objectTags)
    {
        ArgumentNullException.ThrowIfNull(objectTags);

        var isHistorical = objectTags.Contains(HistoricalTag, StringComparer.OrdinalIgnoreCase)
            || objectTags.Contains("Artifact", StringComparer.OrdinalIgnoreCase)
            || objectTags.Contains("Relic", StringComparer.OrdinalIgnoreCase)
            || objectTags.Contains("Document", StringComparer.OrdinalIgnoreCase)
            || objectTags.Contains("Monument", StringComparer.OrdinalIgnoreCase)
            || objectTags.Contains("HistoricalRemains", StringComparer.OrdinalIgnoreCase);

        _logger.LogDebug(
            "Lore Keeper: Historical object check — Tags: [{Tags}], Result: {IsHistorical}",
            string.Join(", ", objectTags),
            isHistorical);

        return isHistorical;
    }

    /// <summary>
    /// Determines whether Layer 3 should auto-succeed for the given object
    /// and layer number based on Lore Keeper passive.
    /// </summary>
    /// <param name="objectTags">Tags associated with the object being examined.</param>
    /// <param name="layerNumber">The examination layer number being attempted.</param>
    /// <returns><c>true</c> if Lore Keeper grants auto-success for this layer.</returns>
    public bool ShouldAutoSucceedLayer3(IReadOnlyList<string> objectTags, int layerNumber)
    {
        if (layerNumber != LoreKeeperAutoSucceedLayer)
        {
            _logger.LogDebug(
                "Lore Keeper: Layer {Layer} is not Layer {AutoLayer}, " +
                "auto-succeed does not apply",
                layerNumber,
                LoreKeeperAutoSucceedLayer);
            return false;
        }

        var shouldAutoSucceed = IsHistoricalObject(objectTags);

        if (shouldAutoSucceed)
        {
            _logger.LogInformation(
                "Lore Keeper: AUTO-SUCCESS on Layer {Layer} for historical object. " +
                "Tags: [{Tags}]",
                layerNumber,
                string.Join(", ", objectTags));
        }

        return shouldAutoSucceed;
    }

    /// <summary>
    /// Calculates the Lore Insight generated by Lore Keeper on first
    /// examination of a historical object.
    /// </summary>
    /// <param name="isFirstExamination">Whether this is the first examination of the object.</param>
    /// <returns>
    /// <see cref="LoreKeeperFirstExamInsight"/> (2) if first examination,
    /// 0 otherwise.
    /// </returns>
    public int GenerateLoreKeeperInsight(bool isFirstExamination)
    {
        var insight = isFirstExamination ? LoreKeeperFirstExamInsight : 0;

        if (isFirstExamination)
        {
            _logger.LogInformation(
                "Lore Keeper: First examination — generated {Insight} Lore Insight",
                insight);
        }
        else
        {
            _logger.LogDebug(
                "Lore Keeper: Re-examination — no additional Lore Insight generated");
        }

        return insight;
    }

    // ═══════ Ancient Knowledge (Passive) ═══════

    /// <summary>
    /// Creates a bonus lore revelation from the Ancient Knowledge passive ability.
    /// </summary>
    /// <param name="sourceExaminationId">ID of the triggering examination.</param>
    /// <param name="loreType">Type of lore being revealed.</param>
    /// <param name="title">Summary title for the revelation.</param>
    /// <param name="content">Full content of the revelation.</param>
    /// <param name="relatedLocations">Optional related location IDs.</param>
    /// <param name="relatedFigures">Optional related historical figure names.</param>
    /// <returns>A new <see cref="LoreRevelation"/> instance.</returns>
    public LoreRevelation GenerateBonusLore(
        Guid sourceExaminationId,
        LoreRevelationType loreType,
        string title,
        string content,
        IEnumerable<Guid>? relatedLocations = null,
        IEnumerable<string>? relatedFigures = null)
    {
        var revelation = LoreRevelation.Create(
            sourceExaminationId, loreType, title, content,
            relatedLocations, relatedFigures);

        _logger.LogInformation(
            "Ancient Knowledge: Bonus lore revealed — {LoreType}: \"{Title}\". " +
            "ExaminationId: {ExaminationId}. RevelationId: {RevelationId}. " +
            "+{Insight} Lore Insight",
            loreType,
            title,
            sourceExaminationId,
            revelation.RevelationId,
            revelation.InsightGenerated);

        return revelation;
    }

    /// <summary>
    /// Calculates the number of bonus lore entries to reveal based on
    /// examination success level.
    /// </summary>
    /// <param name="isExpertSuccess">Whether the examination achieved Expert level.</param>
    /// <param name="isMasterSuccess">Whether the examination achieved Master level.</param>
    /// <returns>
    /// 2 for Master success, 1 for Expert success, 0 otherwise.
    /// </returns>
    public int CalculateBonusLoreCount(bool isExpertSuccess, bool isMasterSuccess)
    {
        int count;
        if (isMasterSuccess)
        {
            count = AncientKnowledgeMasterLoreCount;
        }
        else if (isExpertSuccess)
        {
            count = AncientKnowledgeExpertLoreCount;
        }
        else
        {
            count = 0;
        }

        _logger.LogDebug(
            "Ancient Knowledge: Bonus lore count calculated — Expert: {Expert}, " +
            "Master: {Master}, Result: {Count} entries",
            isExpertSuccess, isMasterSuccess, count);

        return count;
    }

    /// <summary>
    /// Calculates the total Lore Insight generated from bonus lore entries.
    /// </summary>
    /// <param name="loreCount">Number of bonus lore entries revealed.</param>
    /// <returns>Total Lore Insight generated (1 per entry).</returns>
    public int CalculateAncientKnowledgeInsight(int loreCount)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(loreCount);

        var insight = loreCount * AncientKnowledgeInsightPerLore;

        _logger.LogInformation(
            "Ancient Knowledge: {LoreCount} bonus lore entries generated " +
            "+{TotalInsight} Lore Insight",
            loreCount, insight);

        return insight;
    }

    // ═══════ Voice of the Giants (Capstone) ═══════

    /// <summary>
    /// Activates dormant Jötun technology, creating an activation record
    /// with generated effects based on the technology type.
    /// </summary>
    /// <param name="technologyId">ID of the dormant technology.</param>
    /// <param name="type">Type of Jötun technology.</param>
    /// <param name="name">Display name of the technology.</param>
    /// <param name="activatorId">ID of the activating character.</param>
    /// <param name="durationMinutes">
    /// Duration in minutes. Defaults to <see cref="DefaultActivationDurationMinutes"/>.
    /// </param>
    /// <returns>A new <see cref="ActivatedTechnology"/> instance with generated effects.</returns>
    public ActivatedTechnology ActivateTechnology(
        Guid technologyId,
        JotunTechnologyType type,
        string name,
        Guid activatorId,
        int durationMinutes = DefaultActivationDurationMinutes)
    {
        var effects = GenerateEffects(type);
        var activation = ActivatedTechnology.Create(
            technologyId, type, name, activatorId, effects, durationMinutes);

        _logger.LogInformation(
            "Voice of the Giants: {ActivatorId} activated {TechnologyName} ({Type}). " +
            "Duration: {Duration} minutes. Effects: {EffectCount}. " +
            "ActivationId: {ActivationId}. " +
            "Cost: {APCost} AP + {InsightCost} Lore Insight",
            activatorId,
            name,
            type,
            durationMinutes,
            effects.Count,
            activation.ActivationId,
            VoiceOfTheGiantsAPCost,
            VoiceOfTheGiantsInsightCost);

        return activation;
    }

    /// <summary>
    /// Generates effects for the given technology type.
    /// </summary>
    /// <param name="type">The type of technology being activated.</param>
    /// <returns>A list of effects produced by the activation.</returns>
    public IReadOnlyList<TechnologyEffect> GenerateEffects(JotunTechnologyType type)
    {
        var effect = type switch
        {
            JotunTechnologyType.PowerNode => new TechnologyEffect
            {
                EffectType = "PowerRestore",
                Description = "Restores power to all connected systems in this area",
                IsContinuous = true
            },
            JotunTechnologyType.MedicalBay => new TechnologyEffect
            {
                EffectType = "AreaHealing",
                TargetArea = 30,
                Value = 24,
                Description = "All creatures in 30-foot radius restored to full health",
                IsContinuous = false
            },
            JotunTechnologyType.SensorArray => new TechnologyEffect
            {
                EffectType = "Revelation",
                TargetArea = 300,
                Description = "All hidden creatures and objects revealed in 300-foot radius",
                IsContinuous = true
            },
            JotunTechnologyType.DefenseGrid => new TechnologyEffect
            {
                EffectType = "AutonomousDefense",
                TargetArea = 150,
                Description = "Automated defenses engage against non-Jötun targets",
                IsContinuous = true
            },
            JotunTechnologyType.TransportSystem => new TechnologyEffect
            {
                EffectType = "FastTravel",
                Description = "Enables rapid transit between connected terminals",
                IsContinuous = true
            },
            JotunTechnologyType.ArchiveTerminal => new TechnologyEffect
            {
                EffectType = "DataAccess",
                Description = "Unlocks all restricted archive data (no hacking required)",
                IsContinuous = false
            },
            JotunTechnologyType.Fabricator => new TechnologyEffect
            {
                EffectType = "Crafting",
                Description = "Enables creation of advanced items (beyond normal crafting)",
                IsContinuous = false
            },
            JotunTechnologyType.EnvironmentalControl => new TechnologyEffect
            {
                EffectType = "EnvironmentModification",
                Description = "Adjusts temperature, atmosphere, lighting in area",
                IsContinuous = true
            },
            _ => new TechnologyEffect
            {
                EffectType = "Unknown",
                Description = "Unknown technology effect",
                IsContinuous = false
            }
        };

        _logger.LogDebug(
            "Voice of the Giants: Generated effect for {Type} — " +
            "{EffectType}: {Description}",
            type, effect.EffectType, effect.Description);

        return new List<TechnologyEffect> { effect }.AsReadOnly();
    }

    /// <summary>
    /// Checks whether Voice of the Giants has already been used in the current
    /// long rest period by the specified character.
    /// </summary>
    /// <param name="usedRestIds">
    /// Set of rest-period IDs during which the character has already used
    /// Voice of the Giants.
    /// </param>
    /// <param name="currentRestId">The current rest-period ID.</param>
    /// <returns><c>true</c> if the character has already used Voice of the Giants.</returns>
    public bool HasUsedVoiceOfGiants(
        IReadOnlyList<Guid> usedRestIds,
        Guid currentRestId)
    {
        ArgumentNullException.ThrowIfNull(usedRestIds);

        var hasUsed = usedRestIds.Contains(currentRestId);

        if (hasUsed)
        {
            _logger.LogWarning(
                "Voice of the Giants REJECTED: already used this long rest. " +
                "RestId: {RestId}",
                currentRestId);
        }

        return hasUsed;
    }

    /// <summary>
    /// Records that Voice of the Giants has been used during the current
    /// rest period.
    /// </summary>
    /// <param name="usedRestIds">Mutable list to record usage in.</param>
    /// <param name="currentRestId">The current rest-period ID to record.</param>
    /// <returns>Updated list with the current rest ID added.</returns>
    public IReadOnlyList<Guid> MarkVoiceOfGiantsUsed(
        List<Guid> usedRestIds,
        Guid currentRestId)
    {
        ArgumentNullException.ThrowIfNull(usedRestIds);

        usedRestIds.Add(currentRestId);

        _logger.LogInformation(
            "Voice of the Giants: Usage recorded for rest period {RestId}. " +
            "Total uses tracked: {TotalUses}",
            currentRestId,
            usedRestIds.Count);

        return usedRestIds.AsReadOnly();
    }

    // ═══════ Prerequisite Helpers ═══════

    /// <summary>
    /// Checks whether Tier 3 abilities can be unlocked based on PP invested.
    /// Requires 16 PP invested in the Jötun-Reader tree.
    /// </summary>
    /// <param name="ppInvested">Total PP invested.</param>
    /// <returns>True if threshold is met.</returns>
    public bool CanUnlockTier3(int ppInvested)
    {
        var canUnlock = ppInvested >= Tier3Threshold;

        _logger.LogDebug(
            "Jötun-Reader Tier 3 unlock check: PP invested {PPInvested}, " +
            "threshold {Threshold}, result {CanUnlock}",
            ppInvested, Tier3Threshold, canUnlock);

        return canUnlock;
    }

    /// <summary>
    /// Checks whether the Capstone ability can be unlocked based on PP invested.
    /// Requires 24 PP invested in the Jötun-Reader tree.
    /// </summary>
    /// <param name="ppInvested">Total PP invested.</param>
    /// <returns>True if threshold is met.</returns>
    public bool CanUnlockCapstone(int ppInvested)
    {
        var canUnlock = ppInvested >= CapstoneThreshold;

        _logger.LogDebug(
            "Jötun-Reader Capstone unlock check: PP invested {PPInvested}, " +
            "threshold {Threshold}, result {CanUnlock}",
            ppInvested, CapstoneThreshold, canUnlock);

        return canUnlock;
    }
}
