using RuneAndRust.Core.Enums;

namespace RuneAndRust.Core.Models.Magic;

/// <summary>
/// Represents the result of a spell cast attempt, including success status,
/// damage/healing values, and any status effects applied.
/// </summary>
/// <remarks>
/// See: v0.4.3c (The Incantation) for implementation details.
/// Mirrors AbilityResult pattern but adds spell-specific properties.
/// </remarks>
public sealed record MagicResult
{
    /// <summary>
    /// Gets whether the spell cast was successful.
    /// </summary>
    public bool Success { get; init; }

    /// <summary>
    /// Gets the narrative message describing the cast result.
    /// </summary>
    public string Message { get; init; } = string.Empty;

    /// <summary>
    /// Gets the reason for cast failure, if any.
    /// </summary>
    public CastFailureReason FailureReason { get; init; } = CastFailureReason.None;

    /// <summary>
    /// Gets the total damage dealt by the spell.
    /// </summary>
    public int TotalDamage { get; init; }

    /// <summary>
    /// Gets the total healing provided by the spell.
    /// </summary>
    public int TotalHealing { get; init; }

    /// <summary>
    /// Gets the list of status effects applied by the spell.
    /// </summary>
    public IReadOnlyList<StatusEffectType>? StatusesApplied { get; init; }

    /// <summary>
    /// Gets the amount of flux generated by this spell cast.
    /// </summary>
    public int FluxGenerated { get; init; }

    /// <summary>
    /// Gets whether this result indicates a charged spell initiation (not release).
    /// </summary>
    public bool IsChargeInitiation { get; init; }

    /// <summary>
    /// Gets whether this result indicates a backlash occurred (v0.4.3d).
    /// Backlash means the spell fizzled but damage was dealt to the caster.
    /// </summary>
    public bool IsBacklash { get; init; }

    /// <summary>
    /// Gets the backlash severity if IsBacklash is true (v0.4.3d).
    /// </summary>
    public BacklashSeverity BacklashSeverity { get; init; } = BacklashSeverity.None;

    /// <summary>
    /// Creates a successful spell cast result.
    /// </summary>
    /// <param name="message">The narrative message.</param>
    /// <param name="damage">Total damage dealt.</param>
    /// <param name="healing">Total healing provided.</param>
    /// <param name="statuses">Status effects applied.</param>
    /// <param name="flux">Flux generated.</param>
    /// <returns>A successful MagicResult.</returns>
    public static MagicResult Ok(
        string message,
        int damage = 0,
        int healing = 0,
        IReadOnlyList<StatusEffectType>? statuses = null,
        int flux = 0)
    {
        return new MagicResult
        {
            Success = true,
            Message = message,
            FailureReason = CastFailureReason.None,
            TotalDamage = damage,
            TotalHealing = healing,
            StatusesApplied = statuses,
            FluxGenerated = flux,
            IsChargeInitiation = false,
            IsBacklash = false,
            BacklashSeverity = BacklashSeverity.None
        };
    }

    /// <summary>
    /// Creates a charge initiation result (spell is charging, not yet released).
    /// </summary>
    /// <param name="message">The telegraph message.</param>
    /// <param name="flux">Flux generated on initiation.</param>
    /// <returns>A charge initiation MagicResult.</returns>
    public static MagicResult ChargeInitiated(string message, int flux = 0)
    {
        return new MagicResult
        {
            Success = true,
            Message = message,
            FailureReason = CastFailureReason.None,
            TotalDamage = 0,
            TotalHealing = 0,
            StatusesApplied = null,
            FluxGenerated = flux,
            IsChargeInitiation = true,
            IsBacklash = false,
            BacklashSeverity = BacklashSeverity.None
        };
    }

    /// <summary>
    /// Creates a failed spell cast result.
    /// </summary>
    /// <param name="reason">The reason for failure.</param>
    /// <param name="message">Optional custom failure message.</param>
    /// <returns>A failed MagicResult.</returns>
    public static MagicResult Failure(CastFailureReason reason, string? message = null)
    {
        var defaultMessage = reason switch
        {
            CastFailureReason.NotMagicUser => "You lack the magical aptitude to cast spells.",
            CastFailureReason.InsufficientAP => "Not enough Aether Points.",
            CastFailureReason.InvalidTarget => "Invalid target for this spell.",
            CastFailureReason.OutOfRange => "Target is out of range.",
            CastFailureReason.TargetDead => "Cannot target a dead combatant.",
            CastFailureReason.Silenced => "You are silenced and cannot cast spells.",
            CastFailureReason.ConcentrationConflict => "You are already concentrating on another spell.",
            CastFailureReason.OnCooldown => "That spell is on cooldown.",
            CastFailureReason.SpellNotKnown => "You do not know that spell.",
            CastFailureReason.InvalidCombatState => "You cannot cast spells right now.",
            CastFailureReason.SoulLost => "Your soul has been consumed. Magic no longer answers.",
            _ => "Spell cast failed."
        };

        return new MagicResult
        {
            Success = false,
            Message = message ?? defaultMessage,
            FailureReason = reason,
            TotalDamage = 0,
            TotalHealing = 0,
            StatusesApplied = null,
            FluxGenerated = 0,
            IsChargeInitiation = false,
            IsBacklash = false,
            BacklashSeverity = BacklashSeverity.None
        };
    }

    /// <summary>
    /// Creates a backlash result where the spell fizzled and damaged the caster (v0.4.3d).
    /// </summary>
    /// <param name="message">The narrative message describing the backlash.</param>
    /// <param name="damageToSelf">Damage dealt to the caster.</param>
    /// <param name="severity">The backlash severity level.</param>
    /// <param name="flux">Partial flux generated (half of spell cost).</param>
    /// <returns>A backlash MagicResult.</returns>
    public static MagicResult Backlash(
        string message,
        int damageToSelf,
        BacklashSeverity severity,
        int flux = 0)
    {
        return new MagicResult
        {
            Success = false,
            Message = message,
            FailureReason = CastFailureReason.None, // Not a validation failure
            TotalDamage = damageToSelf, // Damage to caster (self-harm)
            TotalHealing = 0,
            StatusesApplied = severity >= BacklashSeverity.Major
                ? new List<StatusEffectType> { StatusEffectType.AetherSickness }
                : null,
            FluxGenerated = flux,
            IsChargeInitiation = false,
            IsBacklash = true,
            BacklashSeverity = severity
        };
    }
}
