using RuneAndRust.Core.Enums;

namespace RuneAndRust.Core.Events;

/// <summary>
/// Published when a spell is cast during combat (v0.4.3c - The Incantation).
/// Consumed by AudioEventListener and UI components for audio/visual feedback.
/// </summary>
/// <param name="CasterId">The unique identifier of the caster.</param>
/// <param name="CasterName">The display name of the caster.</param>
/// <param name="SpellId">The unique identifier of the spell cast.</param>
/// <param name="SpellName">The display name of the spell.</param>
/// <param name="School">The spell's school (Destruction, Restoration, etc.).</param>
/// <param name="TargetId">The unique identifier of the target (if any).</param>
/// <param name="TargetName">The display name of the target (if any).</param>
/// <param name="FluxGenerated">The amount of flux generated by this cast.</param>
/// <param name="IsChargeInitiation">True if this is a charge initiation, not a release.</param>
/// <param name="DamageDealt">Total damage dealt by the spell.</param>
/// <param name="HealingDone">Total healing provided by the spell.</param>
public record SpellCastEvent(
    Guid CasterId,
    string CasterName,
    Guid SpellId,
    string SpellName,
    SpellSchool School,
    Guid? TargetId,
    string? TargetName,
    int FluxGenerated,
    bool IsChargeInitiation,
    int DamageDealt = 0,
    int HealingDone = 0)
{
    /// <summary>
    /// Returns true if this spell dealt damage.
    /// </summary>
    public bool IsDamaging => DamageDealt > 0;

    /// <summary>
    /// Returns true if this spell provided healing.
    /// </summary>
    public bool IsHealing => HealingDone > 0;

    /// <summary>
    /// Returns true if this is a self-targeted spell.
    /// </summary>
    public bool IsSelfTargeted => TargetId == CasterId;
}
