// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RuneAndRust.Persistence.Data;

#nullable disable

namespace RuneAndRust.Persistence.Migrations
{
    [DbContext(typeof(RuneAndRustDbContext))]
    [Migration("20260101000000_Add_FactionDialogueNpcSpell_Systems")]
    partial class Add_FactionDialogueNpcSpell_Systems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a partial model snapshot for this migration only.
            // The full model is in RuneAndRustDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
