// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RuneAndRust.Persistence.Data;

#nullable disable

namespace RuneAndRust.Persistence.Migrations
{
    [DbContext(typeof(RuneAndRustDbContext))]
    partial class RuneAndRustDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RuneAndRust.Core.Entities.ActiveAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AetherCost")
                        .HasColumnType("integer");

                    b.Property<int?>("Archetype")
                        .HasColumnType("integer");

                    b.Property<int>("ChargeTurns")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownTurns")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EffectScript")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("InterruptThreshold")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Range")
                        .HasColumnType("integer");

                    b.Property<int>("StaminaCost")
                        .HasColumnType("integer");

                    b.Property<string>("TelegraphMessage")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Archetype", "Tier");

                    b.ToTable("ActiveAbilities", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.AmbientCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BiomeTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("TickChance")
                        .HasColumnType("real");

                    b.Property<string>("TickScript")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("AmbientConditions", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.BiomeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableTemplates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BiomeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("BranchingProbability")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DescriptorCategories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MaxRoomCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinRoomCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("SecretRoomProbability")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BiomeId")
                        .IsUnique();

                    b.ToTable("BiomeDefinitions", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.BiomeElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssociatedDataId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BiomeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SpawnCost")
                        .HasColumnType("integer");

                    b.Property<string>("SpawnRules")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BiomeId");

                    b.HasIndex("ElementType");

                    b.ToTable("BiomeElements", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ActiveStatusEffects")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Archetype")
                        .HasColumnType("integer");

                    b.Property<int>("Background")
                        .HasColumnType("integer");

                    b.Property<int>("Corruption")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentAp")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStamina")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentBonuses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Finesse")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Legend")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Lineage")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAp")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("integer");

                    b.Property<int>("Might")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProgressionPoints")
                        .HasColumnType("integer");

                    b.Property<int>("PsychicStress")
                        .HasColumnType("integer");

                    b.Property<int>("Sturdiness")
                        .HasColumnType("integer");

                    b.Property<string>("UnlockedSpecializationIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Will")
                        .HasColumnType("integer");

                    b.Property<int>("Wits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.CharacterFactionStanding", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("FactionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "FactionType");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FactionType");

                    b.ToTable("CharacterFactionStandings", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.CharacterSpecializationProgress", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterId", "NodeId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("NodeId");

                    b.ToTable("CharacterSpecializationProgress", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.CodexEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalFragments")
                        .HasColumnType("integer");

                    b.Property<string>("UnlockThresholds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("CodexEntries", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DataCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CodexEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FragmentContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CodexEntryId");

                    b.ToTable("DataCaptures", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DialogueNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreeId", "NodeId")
                        .IsUnique();

                    b.ToTable("DialogueNodes", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DialogueOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Effects")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("NextNodeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VisibilityMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "DisplayOrder");

                    b.ToTable("DialogueOptions", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DialogueTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AssociatedFaction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NpcName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NpcTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RootNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TreeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedFaction");

                    b.HasIndex("TreeId")
                        .IsUnique();

                    b.ToTable("DialogueTrees", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Faction", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultReputation")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Type");

                    b.ToTable("Factions", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.InteractableObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DetailedDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExpertDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("HasBeenExamined")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBeenSearched")
                        .HasColumnType("boolean");

                    b.Property<int>("HighestExaminationTier")
                        .HasColumnType("integer");

                    b.Property<bool>("IsContainer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LockDifficulty")
                        .HasColumnType("integer");

                    b.Property<int?>("LootTier")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("InteractableObjects", (string)null);

                    b.HasDiscriminator<int>("ObjectType").HasValue(4);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SlotPosition")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("IsEquipped");

                    b.HasIndex("ItemId");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DetailedDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemDiscriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxStackSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemType");

                    b.HasIndex("Name");

                    b.HasIndex("Quality");

                    b.ToTable("Items", (string)null);

                    b.HasDiscriminator<string>("ItemDiscriminator").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.ItemProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatModifiers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemProperties", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Npc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DialogueTreeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Faction")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHostile")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DialogueTreeId");

                    b.HasIndex("Faction");

                    b.HasIndex("RoomId");

                    b.ToTable("Npcs", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BiomeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ConditionId")
                        .HasColumnType("uuid");

                    b.Property<int>("DangerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Exits")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<int[]>("Features")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("IsStartingRoom")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<int>("PositionZ")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.RoomTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adjectives")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BiomeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionTemplates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaxConnectionPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MinConnectionPoints")
                        .HasColumnType("integer");

                    b.Property<string>("NameTemplates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValidConnections")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Archetype");

                    b.HasIndex("BiomeId");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.ToTable("RoomTemplates", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.SaveGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("SerializedState")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SlotNumber")
                        .IsUnique();

                    b.ToTable("SaveGames", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RequiredArchetype")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequiredArchetype");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Specializations", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.SpecializationNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("CostPP")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentNodeIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("Tier");

                    b.ToTable("SpecializationNodes", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApCost")
                        .HasColumnType("integer");

                    b.Property<int?>("Archetype")
                        .HasColumnType("integer");

                    b.Property<int>("BasePower")
                        .HasColumnType("integer");

                    b.Property<int>("ChargeTurns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EffectScript")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FluxCost")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Range")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresConcentration")
                        .HasColumnType("boolean");

                    b.Property<int>("School")
                        .HasColumnType("integer");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<string>("TelegraphMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Archetype");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Range");

                    b.HasIndex("School");

                    b.HasIndex("TargetType");

                    b.HasIndex("Tier");

                    b.ToTable("Spells", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Trauma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Trauma");
                });

            modelBuilder.Entity("RuneAndRust.Core.Models.HazardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BiomeTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EffectScript")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HazardType")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCooldown")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("OneTimeUse")
                        .HasColumnType("boolean");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HazardTemplates", (string)null);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DynamicHazard", b =>
                {
                    b.HasBaseType("RuneAndRust.Core.Entities.InteractableObject");

                    b.Property<int>("CooldownRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("DamageThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("EffectScript")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HazardType")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCooldown")
                        .HasColumnType("integer");

                    b.Property<bool>("OneTimeUse")
                        .HasColumnType("boolean");

                    b.Property<int?>("RequiredDamageType")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasIndex("RoomId");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Equipment", b =>
                {
                    b.HasBaseType("RuneAndRust.Core.Entities.Item");

                    b.Property<string>("AttributeBonuses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentDurability")
                        .HasColumnType("integer");

                    b.Property<int>("DamageDie")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("integer");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<int>("SoakBonus")
                        .HasColumnType("integer");

                    b.HasIndex("Slot");

                    b.HasDiscriminator().HasValue("Equipment");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.BiomeElement", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.BiomeDefinition", null)
                        .WithMany()
                        .HasForeignKey("BiomeId")
                        .HasPrincipalKey("BiomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.CharacterFactionStanding", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.Character", "Character")
                        .WithMany("FactionStandings")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuneAndRust.Core.Entities.Faction", "Faction")
                        .WithMany("CharacterStandings")
                        .HasForeignKey("FactionType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.CharacterSpecializationProgress", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.Character", "Character")
                        .WithMany("SpecializationProgress")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuneAndRust.Core.Entities.SpecializationNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DataCapture", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.CodexEntry", "CodexEntry")
                        .WithMany("Fragments")
                        .HasForeignKey("CodexEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CodexEntry");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DialogueNode", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.DialogueTree", "Tree")
                        .WithMany("Nodes")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DialogueOption", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.DialogueNode", "Node")
                        .WithMany("Options")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.InventoryItem", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuneAndRust.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.ItemProperty", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.Item", null)
                        .WithMany("Properties")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Npc", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.Room", "Room")
                        .WithMany("Npcs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Room", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.AmbientCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionId");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.SpecializationNode", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.ActiveAbility", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RuneAndRust.Core.Entities.Specialization", "Specialization")
                        .WithMany("Nodes")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Trauma", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.Character", null)
                        .WithMany("ActiveTraumas")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DynamicHazard", b =>
                {
                    b.HasOne("RuneAndRust.Core.Entities.Room", null)
                        .WithMany("Hazards")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Character", b =>
                {
                    b.Navigation("ActiveTraumas");

                    b.Navigation("FactionStandings");

                    b.Navigation("Inventory");

                    b.Navigation("SpecializationProgress");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.CodexEntry", b =>
                {
                    b.Navigation("Fragments");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DialogueNode", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.DialogueTree", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Faction", b =>
                {
                    b.Navigation("CharacterStandings");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Item", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Room", b =>
                {
                    b.Navigation("Hazards");

                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("RuneAndRust.Core.Entities.Specialization", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
