using System.Text.Json;
using FluentAssertions;
using RuneAndRust.Core.Enums;
using RuneAndRust.Core.Models;
using RuneAndRust.Core.Serialization;
using CharacterEntity = RuneAndRust.Core.Entities.Character;
using TraumaEntity = RuneAndRust.Core.Entities.Trauma;

namespace RuneAndRust.Tests.Core.Serialization;

/// <summary>
/// Tests for GameStateContext source-generated JSON serialization (v0.3.18c).
/// Verifies that the source generator produces valid serialization metadata
/// and that round-trip serialization preserves all data.
/// </summary>
public class GameStateContextTests
{
    [Fact]
    public void Context_IsCompilerGenerated()
    {
        // Verify the source generator produced the context
        GameStateContext.Default.Should().NotBeNull();
        GameStateContext.Default.GameState.Should().NotBeNull(
            "GameStateContext.Default.GameState should be generated by the source generator");
    }

    [Fact]
    public void RoundTrip_EmptyGameState_Preserves()
    {
        // Arrange
        var original = new GameState
        {
            Phase = GamePhase.MainMenu,
            TurnCount = 0,
            IsSessionActive = false,
            CurrentRoomId = null,
            CurrentCharacter = null
        };

        // Act
        var json = JsonSerializer.Serialize(original, GameStateContext.Default.GameState);
        var deserialized = JsonSerializer.Deserialize(json, GameStateContext.Default.GameState);

        // Assert
        deserialized.Should().NotBeNull();
        deserialized!.Phase.Should().Be(GamePhase.MainMenu);
        deserialized.TurnCount.Should().Be(0);
        deserialized.IsSessionActive.Should().BeFalse();
        deserialized.CurrentRoomId.Should().BeNull();
        deserialized.CurrentCharacter.Should().BeNull();
    }

    [Fact]
    public void RoundTrip_WithCharacter_Preserves()
    {
        // Arrange
        var character = new CharacterEntity
        {
            Id = Guid.NewGuid(),
            Name = "Test Hero",
            Lineage = LineageType.RuneMarked,
            Archetype = ArchetypeType.Mystic,
            Background = BackgroundType.Scholar,
            Sturdiness = 6,
            Might = 4,
            Wits = 8,
            Will = 7,
            Finesse = 5,
            MaxHP = 110,
            CurrentHP = 85,
            MaxStamina = 65,
            CurrentStamina = 50,
            PsychicStress = 25,
            Corruption = 10,
            ExperiencePoints = 500,
            Level = 2
        };

        var original = new GameState
        {
            Phase = GamePhase.Exploration,
            TurnCount = 42,
            IsSessionActive = true,
            CurrentRoomId = Guid.NewGuid(),
            CurrentCharacter = character
        };

        // Act
        var json = JsonSerializer.Serialize(original, GameStateContext.Default.GameState);
        var deserialized = JsonSerializer.Deserialize(json, GameStateContext.Default.GameState);

        // Assert
        deserialized.Should().NotBeNull();
        deserialized!.Phase.Should().Be(GamePhase.Exploration);
        deserialized.TurnCount.Should().Be(42);
        deserialized.IsSessionActive.Should().BeTrue();
        deserialized.CurrentRoomId.Should().Be(original.CurrentRoomId);

        deserialized.CurrentCharacter.Should().NotBeNull();
        deserialized.CurrentCharacter!.Name.Should().Be("Test Hero");
        deserialized.CurrentCharacter.Lineage.Should().Be(LineageType.RuneMarked);
        deserialized.CurrentCharacter.Archetype.Should().Be(ArchetypeType.Mystic);
        deserialized.CurrentCharacter.Background.Should().Be(BackgroundType.Scholar);
        deserialized.CurrentCharacter.Sturdiness.Should().Be(6);
        deserialized.CurrentCharacter.Might.Should().Be(4);
        deserialized.CurrentCharacter.Wits.Should().Be(8);
        deserialized.CurrentCharacter.Will.Should().Be(7);
        deserialized.CurrentCharacter.Finesse.Should().Be(5);
        deserialized.CurrentCharacter.CurrentHP.Should().Be(85);
        deserialized.CurrentCharacter.PsychicStress.Should().Be(25);
        deserialized.CurrentCharacter.Corruption.Should().Be(10);
        deserialized.CurrentCharacter.Level.Should().Be(2);
    }

    [Fact]
    public void RoundTrip_WithVisitedRooms_Preserves()
    {
        // Arrange
        var room1 = Guid.NewGuid();
        var room2 = Guid.NewGuid();
        var room3 = Guid.NewGuid();

        var original = new GameState
        {
            Phase = GamePhase.Exploration,
            IsSessionActive = true,
            VisitedRoomIds = new HashSet<Guid> { room1, room2, room3 }
        };

        // Act
        var json = JsonSerializer.Serialize(original, GameStateContext.Default.GameState);
        var deserialized = JsonSerializer.Deserialize(json, GameStateContext.Default.GameState);

        // Assert
        deserialized.Should().NotBeNull();
        deserialized!.VisitedRoomIds.Should().HaveCount(3);
        deserialized.VisitedRoomIds.Should().Contain(room1);
        deserialized.VisitedRoomIds.Should().Contain(room2);
        deserialized.VisitedRoomIds.Should().Contain(room3);
    }

    [Fact]
    public void RoundTrip_WithTraumas_Preserves()
    {
        // Arrange
        var character = new CharacterEntity
        {
            Name = "Traumatized Hero",
            ActiveTraumas = new List<TraumaEntity>
            {
                new TraumaEntity
                {
                    Id = Guid.NewGuid(),
                    DefinitionId = "TRM_NYCTO",
                    Name = "Nyctophobia",
                    Description = "Fear of darkness",
                    Type = TraumaType.Phobia,
                    Source = "Breaking Point in The Deep",
                    IsActive = true
                },
                new TraumaEntity
                {
                    Id = Guid.NewGuid(),
                    DefinitionId = "TRM_COMP",
                    Name = "Compulsive Counter",
                    Description = "Must count everything",
                    Type = TraumaType.Compulsion,
                    Source = "Breaking Point in combat",
                    IsActive = true
                }
            }
        };

        var original = new GameState
        {
            Phase = GamePhase.Exploration,
            IsSessionActive = true,
            CurrentCharacter = character
        };

        // Act
        var json = JsonSerializer.Serialize(original, GameStateContext.Default.GameState);
        var deserialized = JsonSerializer.Deserialize(json, GameStateContext.Default.GameState);

        // Assert
        deserialized.Should().NotBeNull();
        deserialized!.CurrentCharacter.Should().NotBeNull();
        deserialized.CurrentCharacter!.ActiveTraumas.Should().HaveCount(2);
        deserialized.CurrentCharacter.ActiveTraumas[0].Name.Should().Be("Nyctophobia");
        deserialized.CurrentCharacter.ActiveTraumas[0].Type.Should().Be(TraumaType.Phobia);
        deserialized.CurrentCharacter.ActiveTraumas[1].Name.Should().Be("Compulsive Counter");
        deserialized.CurrentCharacter.ActiveTraumas[1].Type.Should().Be(TraumaType.Compulsion);
    }

    [Fact]
    public void RoundTrip_WithCombatState_IsIgnored()
    {
        // Arrange - CombatState is marked [JsonIgnore] and should not be serialized
        var original = new GameState
        {
            Phase = GamePhase.Combat,
            IsSessionActive = true,
            CombatState = new CombatState
            {
                Id = Guid.NewGuid(),
                RoundNumber = 3,
                TurnIndex = 1
            }
        };

        // Act
        var json = JsonSerializer.Serialize(original, GameStateContext.Default.GameState);
        var deserialized = JsonSerializer.Deserialize(json, GameStateContext.Default.GameState);

        // Assert
        deserialized.Should().NotBeNull();
        deserialized!.Phase.Should().Be(GamePhase.Combat);
        // CombatState should be null because it's [JsonIgnore]
        deserialized.CombatState.Should().BeNull(
            "CombatState is marked [JsonIgnore] and should not be serialized");
    }

    [Fact]
    public void Serialization_UsesCamelCase_NamingPolicy()
    {
        // Arrange
        var original = new GameState
        {
            Phase = GamePhase.Exploration,
            TurnCount = 10,
            IsSessionActive = true
        };

        // Act
        var json = JsonSerializer.Serialize(original, GameStateContext.Default.GameState);

        // Assert - verify camelCase property names
        json.Should().Contain("\"phase\":");
        json.Should().Contain("\"turnCount\":");
        json.Should().Contain("\"isSessionActive\":");
        json.Should().NotContain("\"Phase\":");
        json.Should().NotContain("\"TurnCount\":");
        json.Should().NotContain("\"IsSessionActive\":");
    }
}
