// ═══════════════════════════════════════════════════════════════════════════════
// LoreRevelationType.cs
// Types of bonus lore revelations generated by the Ancient Knowledge ability.
// Named LoreRevelationType to avoid collision with the existing LoreType enum
// in ExaminationEnums.cs (which covers discovery-level lore categories).
// Version: 0.20.3c
// ═══════════════════════════════════════════════════════════════════════════════

namespace RuneAndRust.Domain.Enums;

/// <summary>
/// Types of lore revelations that can be discovered through the Ancient Knowledge
/// passive ability.
/// </summary>
/// <remarks>
/// <para>
/// Each type represents a different category of hidden knowledge that the
/// Jötun-Reader can uncover during successful examinations. The type determines
/// the thematic content and potential quest hooks generated.
/// </para>
/// <para>
/// This is distinct from <see cref="LoreType"/>, which categorizes examination
/// discovery sources (DataSlate, Inscription, etc.).
/// </para>
/// </remarks>
/// <seealso cref="JotunReaderAbilityId"/>
public enum LoreRevelationType
{
    /// <summary>Historical context about the item's creation.</summary>
    HistoricalContext = 0,

    /// <summary>Hidden purpose or secret function.</summary>
    HiddenPurpose = 1,

    /// <summary>Related locations for exploration.</summary>
    RelatedLocation = 2,

    /// <summary>Connected historical figures.</summary>
    ConnectedFigure = 3,

    /// <summary>Warnings or dangers.</summary>
    Warning = 4,

    /// <summary>Creation method or craftsmanship.</summary>
    Craftsmanship = 5,

    /// <summary>Legendary status or significance.</summary>
    Legend = 6
}
